import { AbstractBlock } from './block-abstract.js';
import { SimpleBlock } from './block-simple.js';
import { IchosBlock } from './block-ichos.js';
import { PosotitaBlock } from './block-posotita.js';
import { MartyriaBlock } from './block-martyria.js';
import { AgogiBlock } from './block-agogi.js';
import { Ichos } from './ichos.js';
import { Posotita } from './posotita.js';
import { SecondaryCharacter } from './secondary.js';
import { Chronos } from './chronos.js';
import { Gorgon } from './gorgon.js';
import { Alloiosi } from './alloiosi.js';
import { Fthora } from './fthora.js';
import { Chroa } from './chroa.js';
import { Vathmida } from './vathmida.js';
import { Fthongos } from './fthongos.js';
import { MartyrikoSimadi } from './martyriko-simadi.js';
import { Agogi } from './agogi.js';

/**
 * @type {AbstractBlock[]}
 */
export const block_list = [];

block_list.push(
	new IchosBlock(Ichos.plagios_tetartos, Vathmida.ni, Fthora.diatoniki_ni),
	AbstractBlock.newline,
	// Εκ νεότητός μου
	new PosotitaBlock(Posotita.ison, 'Εκ'),
	new PosotitaBlock(Posotita.ison, 'νε'),
	new PosotitaBlock(Posotita.oligon_kentima_dipla, 'ο'),
	new PosotitaBlock(Posotita.oligon, 'τη'),
	new PosotitaBlock(Posotita.oligon, 'τος'),
	new PosotitaBlock(Posotita.ison, 'μου'),
	new PosotitaBlock(Posotita.ison, 'ο'),
	new PosotitaBlock(Posotita.ison, 'εχ'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos, 'θρο'),
	new PosotitaBlock(Posotita.apostrofos, 'ος'),
	new PosotitaBlock(Posotita.oligon, 'με'),
	new PosotitaBlock(Posotita.oligon, 'πει'),
	new PosotitaBlock(Posotita.oligon_kentimata, Alloiosi.yfesi_apli, 'ρα'), // NOTE my yfesi
	new PosotitaBlock(Posotita.elafron, 'ζει'),
	new PosotitaBlock(Posotita.ison, 'ταις'),
	new PosotitaBlock(Posotita.ison, 'η'),
	new PosotitaBlock(Posotita.apostrofos, 'δο'),
	new PosotitaBlock(Posotita.oligon_kentimata, SecondaryCharacter.psifiston, Alloiosi.yfesi_apli, 'ναις'),
	new PosotitaBlock(Posotita.apostrofos, 'φλε'),
	new PosotitaBlock(Posotita.apostrofos, 'γει'),
	new PosotitaBlock(Posotita.apostrofos, 'με'),
	new PosotitaBlock(Posotita.ison, 'ε'),
	new PosotitaBlock(Posotita.petasti_ison, 'γω'),
	new PosotitaBlock(Posotita.apostrofos, 'δε'),
	new PosotitaBlock(Posotita.oligon, 'πε'),
	new PosotitaBlock(Posotita.oligon, 'ποι'),
	new PosotitaBlock(Posotita.oligon, Chronos.klasma, 'θως'),
	new PosotitaBlock(Posotita.ison, 'εν'),
	new PosotitaBlock(Posotita.oligon, 'σοι'),
	new PosotitaBlock(Posotita.petasti_apostrofos, 'Κυ'),
	new PosotitaBlock(Posotita.apostrofos, 'ρι'),
	new PosotitaBlock(Posotita.syneches_elafron, 'ε'),
	new PosotitaBlock(Posotita.oligon, 'τρο'),
	new PosotitaBlock(Posotita.oligon, SecondaryCharacter.psifiston, 'που'),
	new PosotitaBlock(Posotita.apostrofos, 'μαι'),
	new PosotitaBlock(Posotita.apostrofos_kentimata, 'του'),
	new PosotitaBlock(Posotita.elafron, Chronos.klasma, 'τον'),
	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.delta),
	AbstractBlock.newline,
	// Οι μισούντες Σιών
	new PosotitaBlock(Posotita.oligon_kentima_dipla, 'Οι'),
	new PosotitaBlock(Posotita.oligon, 'μι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti, SecondaryCharacter.rythmos_trisimos, 'σου'),
	new PosotitaBlock(Posotita.elafron, 'ντες'),
	new PosotitaBlock(Posotita.oligon, 'Σι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon, Chronos.klasma, 'ων'),
	new PosotitaBlock(Posotita.ison, 'γε'),
	new PosotitaBlock(Posotita.ison, 'νη'),
	new PosotitaBlock(Posotita.ison, 'θη'),
	new PosotitaBlock(Posotita.kentimata, 'η'),
	new PosotitaBlock(Posotita.ison, 'τω'),
	new PosotitaBlock(Posotita.elafron, 'σαν'),
	new PosotitaBlock(Posotita.oligon, Chronos.klasma, 'δη'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison, SecondaryCharacter.rythmos_trisimos, 'πριν'),
	new PosotitaBlock(Posotita.ison, 'εκ'),
	new PosotitaBlock(Posotita.ison, 'σπα'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.elafron_apostrofos, 'σθη'),
	new PosotitaBlock(Posotita.kentimata, 'η'),
	new PosotitaBlock(Posotita.ison, 'ναι'),
	new PosotitaBlock(Posotita.elafron, 'ως'),
	new PosotitaBlock(Posotita.oligon_kentimata, 'χορ'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.elafron, Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'τος'),
	new PosotitaBlock(Posotita.oligon, 'συγ'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti, 'κο'),
	new PosotitaBlock(Posotita.apostrofos, 'ψει'),
	new PosotitaBlock(Posotita.oligon, 'γαρ'),
	new PosotitaBlock(Posotita.oligon, 'Χρι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon, Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'στος'),
	SimpleBlock.stavros,
	new PosotitaBlock(Posotita.ison, 'αυ'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_kentimata, Gorgon.gorgon, Alloiosi.yfesi_apli, 'χε'), // NOTE my yfesi
	new PosotitaBlock(Posotita.apostrofos, 'ε'),
	new PosotitaBlock(Posotita.apostrofos, 'νας'),
	new PosotitaBlock(Posotita.ison, 'αυ'),
	new PosotitaBlock(Posotita.elafron_apostrofos, 'των'),
	new PosotitaBlock(Posotita.oligon, 'το'),
	new PosotitaBlock(Posotita.ison, 'μη'),
	new PosotitaBlock(Posotita.elafron, 'βα'),
	new PosotitaBlock(Posotita.oligon_kentimata, 'σα'),
	new PosotitaBlock(Posotita.elafron, Chronos.klasma, 'νων'),
	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.delta),
	AbstractBlock.newline,
	// Δόξα, Και νυν
	SimpleBlock.diastoli,
	new AgogiBlock(Agogi.tacheia),
	new PosotitaBlock(Posotita.oligon_ypsili_dexia,SecondaryCharacter.rythmos_trisimos, 'Δο'),
	new PosotitaBlock(Posotita.ison, 'ξα'),
	new PosotitaBlock(Posotita.ison, 'Πα'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_ison,SecondaryCharacter.rythmos_trisimos, 'τρι'),
	new PosotitaBlock(Posotita.ison, 'και'),
	new PosotitaBlock(Posotita.ison, 'Υι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_ison,SecondaryCharacter.rythmos_trisimos, 'ω'),
	new PosotitaBlock(Posotita.ison, 'και'),
	new PosotitaBlock(Posotita.ison, 'Α'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.apostrofos, 'γι'),
	new PosotitaBlock(Posotita.oligon, 'ω'),
	new PosotitaBlock(Posotita.petasti, 'Πνευ'),
	new PosotitaBlock(Posotita.apostrofos, 'μα'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison,Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'τι'),
	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.delta_teleies),
	new PosotitaBlock(Posotita.chamili, 'και'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_ypsili_dexia,SecondaryCharacter.rythmos_trisimos, 'νυν'),
	new PosotitaBlock(Posotita.ison, 'και'),
	new PosotitaBlock(Posotita.ison, 'α'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti,SecondaryCharacter.rythmos_trisimos, 'ει'),
	new PosotitaBlock(Posotita.apostrofos, 'και'),
	new PosotitaBlock(Posotita.ison, 'εις'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison, 'τους'),
	new PosotitaBlock(Posotita.ison, 'αι'),
	new AgogiBlock(Agogi.metria),
	new PosotitaBlock(Posotita.ison,SecondaryCharacter.psifiston, 'ω'),
	new PosotitaBlock(Posotita.apostrofos, 'νας'),
	new PosotitaBlock(Posotita.apostrofos, 'των'),
	new PosotitaBlock(Posotita.apostrofos, 'αι'),
	new PosotitaBlock(Posotita.oligon_kentimata,SecondaryCharacter.psifiston, 'ω'),
	new PosotitaBlock(Posotita.apostrofos, 'νων'),
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'μην'), // TODO rythmos on klasma
	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.delta),
	AbstractBlock.newline,
	// Αγίω Πνεύματι
	new PosotitaBlock(Posotita.ison, 'Α'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_kentima_dipla, 'γι'),
	new PosotitaBlock(Posotita.oligon, 'ω'),
	new PosotitaBlock(Posotita.oligon, 'Πνευ'),
	new PosotitaBlock(Posotita.ison, 'μα'),
	new PosotitaBlock(Posotita.ison, 'τι'),
	new PosotitaBlock(Posotita.ison, 'το'),
	new PosotitaBlock(Posotita.petasti, 'ζην'),
	new PosotitaBlock(Posotita.apostrofos, 'τα'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_kentimata,Alloiosi.yfesi_apli, SecondaryCharacter.rythmos_trisimos, 'παν'), // NOTE my yfesi
	new PosotitaBlock(Posotita.elafron, 'τα'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti,SecondaryCharacter.rythmos_trisimos, 'φως'),
	new PosotitaBlock(Posotita.apostrofos, 'εκ'),
	new PosotitaBlock(Posotita.ison, 'φω'),
	SimpleBlock.diastoli,
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos, 'το'),
	new PosotitaBlock(Posotita.apostrofos, 'ος'),
	new PosotitaBlock(Posotita.oligon, 'Θε'),
	new PosotitaBlock(Posotita.oligon, 'ος'),
	new PosotitaBlock(Posotita.oligon_kentimata,Alloiosi.yfesi_apli, 'με'), // NOTE my yfesi
	new PosotitaBlock(Posotita.elafron,Chronos.klasma, 'γας'),
	new PosotitaBlock(Posotita.ison, 'συν'),
	new PosotitaBlock(Posotita.oligon, 'Πα'),
	new PosotitaBlock(Posotita.petasti,Alloiosi.yfesi_apli, 'τρι'), // NOTE my yfesi
	SimpleBlock.stavros,
	new PosotitaBlock(Posotita.elafron, 'υ'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.oligon, 'μνου'),
	new PosotitaBlock(Posotita.ison,SecondaryCharacter.omalon_diplo, 'ου'),
	new PosotitaBlock(Posotita.apostrofos, 'μεν'),
	new PosotitaBlock(Posotita.ison, 'αυ'),
	new PosotitaBlock(Posotita.elafron_apostrofos, 'το'),
	new PosotitaBlock(Posotita.kentimata, 'ο'),
	new PosotitaBlock(Posotita.ison, 'και'),
	new PosotitaBlock(Posotita.elafron, 'τω'),
	new PosotitaBlock(Posotita.oligon_kentimata, 'Λο'),
	new PosotitaBlock(Posotita.elafron,Chronos.klasma, 'γω'),
	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.delta),
	AbstractBlock.newline,
);

block_list.push(
	new IchosBlock(Ichos.protos, Vathmida.pa, Fthora.diatoniki_pa),
	AbstractBlock.newline,
	new PosotitaBlock(Posotita.petasti, 'Κυ'),
	new PosotitaBlock(Posotita.apostrofos, 'ρι'),
	new PosotitaBlock(Posotita.ison, 'ε'),
	SimpleBlock.stavros,
	new PosotitaBlock(Posotita.oligon, 'ε'),
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, SecondaryCharacter.psifiston, 'κε'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'κρα'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.apli, SecondaryCharacter.antikenoma, 'ξα'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'α'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.ison, 'προ'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ο'),
	new PosotitaBlock(Posotita.oligon, 'ος'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti_oligon,SecondaryCharacter.rythmos_tetrasimos, 'σε'), // TODO rythmos on posotita
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'ε'),
	new MartyriaBlock(Fthongos.pa, MartyrikoSimadi.alfa),
	new PosotitaBlock(Posotita.ison, 'ει'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti_kentima,Chronos.klasma, 'σα'),
	new PosotitaBlock(Posotita.apostrofos_kentimata, 'κου'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'σο'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon, SecondaryCharacter.antikenoma, 'ο'),
	new PosotitaBlock(Posotita.apostrofos, 'ον'),
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'μου'),
	new MartyriaBlock(Fthongos.pa, MartyrikoSimadi.alfa),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon_kato, 'ει'),
	new PosotitaBlock(Posotita.oligon, 'σα'),
	new PosotitaBlock(Posotita.oligon,SecondaryCharacter.psifiston, Alloiosi.yfesi_apli, 'α'),
	new PosotitaBlock(Posotita.syneches_elafron, 'κου'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.apli, Gorgon.gorgon, 'ου'),
	new PosotitaBlock(Posotita.ison_kentimata,Gorgon.gorgon, 'σο'),
	new PosotitaBlock(Posotita.apostrofos, 'ον'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos, 'μου'),
	new PosotitaBlock(Posotita.apostrofos, 'ου'),
	new PosotitaBlock(Posotita.oligon, 'Κυ'),
	new PosotitaBlock(Posotita.kentimata_oligon, 'υ'),
	new PosotitaBlock(Posotita.oligon_kentimata,Gorgon.gorgon, 'υ'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'ρι'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon, SecondaryCharacter.antikenoma, 'ι'),
	new PosotitaBlock(Posotita.apostrofos, 'ι'),
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'ε'),
	new MartyriaBlock(Fthongos.pa, MartyrikoSimadi.alfa),
	new PosotitaBlock(Posotita.petasti_kentima, 'Κυ'),
	new PosotitaBlock(Posotita.apostrofos, 'ρι'),
	new PosotitaBlock(Posotita.ison, 'ε'),
	SimpleBlock.stavros,
	new PosotitaBlock(Posotita.oligon, 'ε'),
	new PosotitaBlock(Posotita.oligon_kentimata,SecondaryCharacter.psifiston, Alloiosi.yfesi_apli, 'κε'),
	new PosotitaBlock(Posotita.apostrofos, 'κρα'),
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	new PosotitaBlock(Posotita.petasti_apostrofos,Chronos.klasma, 'ξα'),
	new PosotitaBlock(Posotita.syneches_elafron, 'προ'),
	new PosotitaBlock(Posotita.kentimata, 'ος'),
	new PosotitaBlock(Posotita.oligon_kentimata,Gorgon.gorgon, 'σε'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'ε'),
	new MartyriaBlock(Fthongos.ga, MartyrikoSimadi.nana),
	new PosotitaBlock(Posotita.elafron, 'ει'),
	new PosotitaBlock(Posotita.ison, 'σα'),
	new PosotitaBlock(Posotita.ison, 'κου'),
	new PosotitaBlock(Posotita.oligon_kentima_kato,Chronos.klasma, SecondaryCharacter.psifiston, 'σο'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon, 'ο'),
	new PosotitaBlock(Posotita.apostrofos, 'ο'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ον'),
	SimpleBlock.diastoli,
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.oligon,SecondaryCharacter.rythmos_trisimos, 'μου'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.digorgon, 'ου'),
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, 'ου'),
	new MartyriaBlock(Fthongos.zo, MartyrikoSimadi.varys),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_ypsili_aristera,Chronos.klasma, SecondaryCharacter.omalon_mono, 'προ'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'σχες'),
	new PosotitaBlock(Posotita.ison, 'τη'),
	new PosotitaBlock(Posotita.apostrofos, 'φω'),
	new PosotitaBlock(Posotita.oligon, 'νη'),
	new PosotitaBlock(Posotita.oligon,SecondaryCharacter.psifiston, 'η'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon, 'η'),
	new PosotitaBlock(Posotita.apostrofos, 'η'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos, 'τη'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'η'),
	new PosotitaBlock(Posotita.oligon, 'ης'),
	SimpleBlock.stavros,
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, 'δε'),
	new PosotitaBlock(Posotita.oligon_kentimata,Gorgon.gorgon, 'η'),
	new PosotitaBlock(Posotita.apostrofos, 'η'),
	new PosotitaBlock(Posotita.oligon_kentimata, 'σε'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'ω'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon, 'ω'),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon, SecondaryCharacter.antikenoma, 'ω'),
	new PosotitaBlock(Posotita.apostrofos, 'ως'),
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'μου'),
	new MartyriaBlock(Fthongos.pa, MartyrikoSimadi.alfa),
	new PosotitaBlock(Posotita.oligon_kentima_dipla, 'εν'),
	new PosotitaBlock(Posotita.ison, 'κε'),
	new PosotitaBlock(Posotita.apostrofos, 'τω'),
	new PosotitaBlock(Posotita.oligon, 'κρα'),
	new PosotitaBlock(Posotita.oligon_ypsili_dexia,Chronos.klasma, SecondaryCharacter.psifiston, 'γε'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'ναι'), // TODO enarmonia fthora
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'με'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.apli, SecondaryCharacter.antikenoma, 'προ'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ος'),
	SimpleBlock.diastoli,
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.oligon_kentima_dipla,SecondaryCharacter.rythmos_tetrasimos, 'σε'), // TODO rythmos to the left
	new PosotitaBlock(Posotita.yporroi,Gorgon.trigorgon, 'ε'),
	new PosotitaBlock(Posotita.apostrofos, 'ε'),
	new PosotitaBlock(Posotita.oligon_kentimata,Gorgon.gorgon, 'ε'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'ε'),
	new MartyriaBlock(Fthongos.ga, MartyrikoSimadi.nana, Fthora.diatoniki_ga),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon_kato, 'ει'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_kentimata, 'σα'),
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'κου'),
	new PosotitaBlock(Posotita.apostrofos_kentimata,Gorgon.gorgon, 'σο'),
	new PosotitaBlock(Posotita.apostrofos, 'ον'),
	new PosotitaBlock(Posotita.syneches_elafron,Chronos.klasma, 'μου'),
	new PosotitaBlock(Posotita.oligon, 'Κυ'),
	new PosotitaBlock(Posotita.kentimata, 'υ'),
	new PosotitaBlock(Posotita.petasti,Chronos.klasma, SecondaryCharacter.psifiston, 'υ'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'υ'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'ρι'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon, 'ι'),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon, SecondaryCharacter.antikenoma, 'ι'),
	new PosotitaBlock(Posotita.apostrofos, 'ι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison,Chronos.dipli, SecondaryCharacter.rythmos_tetrasimos, 'ε'),
	new MartyriaBlock(Fthongos.pa, MartyrikoSimadi.alfa),
	AbstractBlock.newline,
);

block_list.push(
	new IchosBlock(Ichos.protos, Vathmida.pa, Fthora.diatoniki_pa),
	AbstractBlock.newline,
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_kentima,SecondaryCharacter.rythmos_trisimos, 'Δευ'),
	new PosotitaBlock(Posotita.ison, 'τε'),
	new PosotitaBlock(Posotita.apostrofos, 'λα'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon, 'οι'),
	new PosotitaBlock(Posotita.oligon, 'υ'),
	new PosotitaBlock(Posotita.oligon,SecondaryCharacter.psifiston, Alloiosi.yfesi_apli, 'μνη'), // NOTE my yfesi
	new PosotitaBlock(Posotita.apostrofos, 'σω'),
	new PosotitaBlock(Posotita.apostrofos, 'μεν'),
	new PosotitaBlock(Posotita.ison, 'και'),
	new PosotitaBlock(Posotita.ison, 'προ'),
	new PosotitaBlock(Posotita.ison, 'σκυ'),
	new PosotitaBlock(Posotita.apostrofos, 'νη'),
	new PosotitaBlock(Posotita.syneches_elafron, 'σω'),
	new PosotitaBlock(Posotita.oligon, 'μεν'),
	new PosotitaBlock(Posotita.oligon, 'Χρι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'στον'),
	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.delta_teleies),
	new PosotitaBlock(Posotita.ison, 'δο'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon, 'ξα'),
	new PosotitaBlock(Posotita.ison, 'ζο'),
	new PosotitaBlock(Posotita.apostrofos, 'ντες'),
	new PosotitaBlock(Posotita.apostrofos, 'αυ'),
	new PosotitaBlock(Posotita.oligon, 'του'),
	new PosotitaBlock(Posotita.ison, 'την'),
	new PosotitaBlock(Posotita.apostrofos, 'εκ'),
	new PosotitaBlock(Posotita.apostrofos, 'νε'),
	new PosotitaBlock(Posotita.oligon, 'κρων'),
	new PosotitaBlock(Posotita.oligon, 'α'),
	new PosotitaBlock(Posotita.ison,SecondaryCharacter.psifiston, 'να'),
	new PosotitaBlock(Posotita.apostrofos, 'στα'),
	new PosotitaBlock(Posotita.syneches_elafron,Chronos.klasma, 'σιν'),
	new MartyriaBlock(Fthongos.pa, MartyrikoSimadi.alfa),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti_ypsili_dexia,SecondaryCharacter.rythmos_trisimos, 'ο'),
	new PosotitaBlock(Posotita.elafron, 'τι'),
	new PosotitaBlock(Posotita.oligon, 'αυ'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon, 'τος'),
	new PosotitaBlock(Posotita.ison, 'ε'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.ison, 'στι'),
	new PosotitaBlock(Posotita.apostrofos, 'ιν'),
	new PosotitaBlock(Posotita.oligon, 'ο'),
	new PosotitaBlock(Posotita.ison, 'Θε'),
	new PosotitaBlock(Posotita.oligon,SecondaryCharacter.psifiston, Alloiosi.yfesi_apli, 'ος'), // NOTE my yfesi
	new PosotitaBlock(Posotita.apostrofos, 'η'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'μων'),
	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.delta_teleies),
	new PosotitaBlock(Posotita.elafron_apostrofos,Fthora.chromatiki_skliri_pa, 'ο'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon, 'εκ'),
	new PosotitaBlock(Posotita.oligon, 'της'),
	new PosotitaBlock(Posotita.oligon,SecondaryCharacter.psifiston, 'πλα'),
	new PosotitaBlock(Posotita.apostrofos, 'νης'),
	new PosotitaBlock(Posotita.apostrofos, 'του'),
	new PosotitaBlock(Posotita.oligon, 'εχ'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'θρου'),
	new PosotitaBlock(Posotita.ison,Fthora.diatoniki_di, 'τον'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti_ison, 'κο'),
	new PosotitaBlock(Posotita.apostrofos, 'σμον'),
	new PosotitaBlock(Posotita.ison, 'λυ'),
	new PosotitaBlock(Posotita.apostrofos, 'τρω'),
	new PosotitaBlock(Posotita.oligon_kentima_kato,SecondaryCharacter.psifiston, 'σα'),
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.apli, SecondaryCharacter.antikenoma, 'με'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ε'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison,Chronos.dipli, SecondaryCharacter.rythmos_trisimos, 'νος'),
	new MartyriaBlock(Fthongos.pa, MartyrikoSimadi.alfa),
	AbstractBlock.newline,
	new PosotitaBlock(Posotita.oligon_kentima, 'Ευ'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti,Chronos.klasma, 'φρα'),
	new PosotitaBlock(Posotita.apostrofos, 'νθη'),
	new PosotitaBlock(Posotita.apostrofos, 'τε'),
	new PosotitaBlock(Posotita.apostrofos, 'ου'),
	new PosotitaBlock(Posotita.oligon, 'ρα'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'νοι'),
	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.delta_teleies),
	new PosotitaBlock(Posotita.ison, 'σαλ'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_kentima,SecondaryCharacter.psifiston, 'πι'),
	new PosotitaBlock(Posotita.apostrofos,Alloiosi.yfesi_apli, 'ι'), // NOTE my yfesi
	new PosotitaBlock(Posotita.apostrofos, 'σα'),
	new PosotitaBlock(Posotita.apostrofos, 'τε'),
	new PosotitaBlock(Posotita.ison, 'τα'),
	new PosotitaBlock(Posotita.apostrofos, 'θε'),
	new PosotitaBlock(Posotita.oligon,SecondaryCharacter.psifiston, 'με'),
	new PosotitaBlock(Posotita.apostrofos, 'λι'),
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	new PosotitaBlock(Posotita.oligon, 'της'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'γης'),
	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.delta_teleies),
	new PosotitaBlock(Posotita.ison, 'βο'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti_kentima,Chronos.klasma, 'η'),
	new PosotitaBlock(Posotita.apostrofos,Alloiosi.yfesi_apli, 'σα'), // NOTE my yfesi
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	new PosotitaBlock(Posotita.apostrofos, 'τε'),
	new PosotitaBlock(Posotita.syneches_elafron, 'τα'),
	new PosotitaBlock(Posotita.oligon_kentima_dipla, 'ο'),
	new PosotitaBlock(Posotita.ison, 'ρη'),
	new PosotitaBlock(Posotita.ison, 'ευ'),
	new PosotitaBlock(Posotita.apostrofos, 'φρο'),
	new PosotitaBlock(Posotita.ison,SecondaryCharacter.psifiston, 'συ'),
	new PosotitaBlock(Posotita.apostrofos, 'υ'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'νην'),
	new PosotitaBlock(Posotita.oligon_kentima, 'ι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon,SecondaryCharacter.psifiston, 'δου'),
	new PosotitaBlock(Posotita.apostrofos, 'γαρ'),
	new PosotitaBlock(Posotita.apostrofos, 'ο'),
	new PosotitaBlock(Posotita.syneches_elafron, 'Εμ'),
	new PosotitaBlock(Posotita.oligon, 'μα'),
	new PosotitaBlock(Posotita.oligon, 'νου'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'ηλ'),
	new PosotitaBlock(Posotita.elafron_apostrofos, 'τας'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison, 'α'),
	new PosotitaBlock(Posotita.ison, 'μαρ'),
	new PosotitaBlock(Posotita.petasti_ison,Chronos.klasma, Fthora.chromatiki_skliri_di, 'τι'), // TODO thesi fthoras, endeixi fthongou
	new PosotitaBlock(Posotita.syneches_elafron, 'ας'),
	new PosotitaBlock(Posotita.oligon, 'η'),
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, 'μων'),
	new MartyriaBlock(Fthongos.pa, MartyrikoSimadi.skliro),
	new PosotitaBlock(Posotita.oligon_kentima,Fthora.diatoniki_di, 'τω'), // TODO thesi fthoras, pitch change
	new PosotitaBlock(Posotita.ison, 'σταυ'),
	new PosotitaBlock(Posotita.petasti_ison, 'ρω'),
	new PosotitaBlock(Posotita.apostrofos, 'προ'),
	new PosotitaBlock(Posotita.ison,SecondaryCharacter.psifiston, 'ση'),
	new PosotitaBlock(Posotita.apostrofos, 'λω'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'σε'),
	new MartyriaBlock(Fthongos.pa, MartyrikoSimadi.alfa),
	new PosotitaBlock(Posotita.oligon, 'και'),
	new PosotitaBlock(Posotita.oligon, 'ζω'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti,SecondaryCharacter.rythmos_trisimos, 'ην'),
	new PosotitaBlock(Posotita.elafron, 'ο'),
	new PosotitaBlock(Posotita.oligon, 'δι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, 'δους'),
	new PosotitaBlock(Posotita.petasti_ison, 'θα'),
	new PosotitaBlock(Posotita.apostrofos, 'να'),
	new PosotitaBlock(Posotita.syneches_elafron,Chronos.klasma, 'τον'),
	new PosotitaBlock(Posotita.ison,Gorgon.gorgon_kato, 'ε'),
	new PosotitaBlock(Posotita.ison_kentimata,Gorgon.gorgon, 'νε'),
	new PosotitaBlock(Posotita.apostrofos, 'κρω'),
	new PosotitaBlock(Posotita.syneches_elafron,Chronos.klasma, 'σε'),
	new MartyriaBlock(Fthongos.zo, MartyrikoSimadi.varys),
	new PosotitaBlock(Posotita.oligon_ypsili_dexia, 'τον'),
	new PosotitaBlock(Posotita.oligon, 'Α'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon,SecondaryCharacter.psifiston, SecondaryCharacter.rythmos_trisimos, 'δαμ'),
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	new PosotitaBlock(Posotita.apostrofos, 'να'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti, 'στη'),
	new PosotitaBlock(Posotita.apostrofos, 'σας'),
	new PosotitaBlock(Posotita.ison, 'ως'),
	new PosotitaBlock(Posotita.apostrofos, 'φι'),
	new PosotitaBlock(Posotita.oligon_kentima_kato,SecondaryCharacter.psifiston, 'λα'),
	new PosotitaBlock(Posotita.apostrofos, 'αν'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.apli, SecondaryCharacter.antikenoma, 'θρω'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ω'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison,Chronos.dipli, SecondaryCharacter.rythmos_tetrasimos, 'πος'),
	new MartyriaBlock(Fthongos.pa, MartyrikoSimadi.alfa),
	AbstractBlock.newline,
);

block_list.push(
	new IchosBlock(Ichos.defteros, Vathmida.di, Fthora.chromatiki_malaki_di),
	AbstractBlock.newline,
	new PosotitaBlock(Posotita.elafron, 'Κυ'),
	new PosotitaBlock(Posotita.kentimata_oligon, 'υ'),
	new PosotitaBlock(Posotita.oligon_kentimata,Gorgon.gorgon, 'υ'),
	new PosotitaBlock(Posotita.elafron,Chronos.klasma, 'ρι'),
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'ε'),
	SimpleBlock.stavros,
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, 'ε'),
	new PosotitaBlock(Posotita.oligon_kentimata,SecondaryCharacter.psifiston, 'κε'),
	new PosotitaBlock(Posotita.apostrofos, 'κρα'),
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	new PosotitaBlock(Posotita.petasti_apostrofos,Chronos.klasma, 'ξα'),
	new PosotitaBlock(Posotita.syneches_elafron, 'προ'),
	new PosotitaBlock(Posotita.kentimata, 'ος'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon,Chronos.dipli, 'σε'),
	new PosotitaBlock(Posotita.apostrofos, 'ει'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_kentimata,SecondaryCharacter.psifiston, 'σα'),
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'κου'),
	new PosotitaBlock(Posotita.oligon_kentima,Chronos.apli, SecondaryCharacter.antikenoma, 'σο'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ο'),
	new PosotitaBlock(Posotita.ison_kentimata,Gorgon.gorgon_parestigmeno, 'ο'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.ison, 'ο'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ον'),
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'μου'),
	new PosotitaBlock(Posotita.ison, 'ει'),
	new PosotitaBlock(Posotita.kentimata, 'ει'),
	new PosotitaBlock(Posotita.oligon_kentimata, 'σα'),
	new PosotitaBlock(Posotita.apostrofos, 'κου'),
	new PosotitaBlock(Posotita.oligon,SecondaryCharacter.psifiston, 'ου'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon, 'ου'),
	new PosotitaBlock(Posotita.apostrofos, 'ου'),
	new PosotitaBlock(Posotita.petasti, 'σον'),
	new PosotitaBlock(Posotita.elafron, 'μου'),
	new PosotitaBlock(Posotita.ison, 'Κυ'),
	new PosotitaBlock(Posotita.kentimata, 'υ'),
	new PosotitaBlock(Posotita.ison_kentimata, 'υ'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'ρι'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon, 'ι'),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon, SecondaryCharacter.antikenoma, 'ι'),
	new PosotitaBlock(Posotita.apostrofos, 'ι'),
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'ε'),
	new MartyriaBlock(Fthongos.vou, MartyrikoSimadi.defteros_teleies),
	new PosotitaBlock(Posotita.oligon_ypsili_aristera,SecondaryCharacter.psifiston, 'Κυ'),
	new PosotitaBlock(Posotita.apostrofos, 'υ'),
	new PosotitaBlock(Posotita.elafron_kentimata,Gorgon.gorgon_parestigmeno, 'ρι'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.ison, 'ι'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ι'),
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'ε'),
	new PosotitaBlock(Posotita.ison,Gorgon.gorgon_kato, 'ε'),
	new PosotitaBlock(Posotita.oligon_kentima, 'κε'),
	new PosotitaBlock(Posotita.oligon, 'ε'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos, 'κρα'),
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos, 'ξα'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'α'),
	new PosotitaBlock(Posotita.oligon, 'α'),
	new PosotitaBlock(Posotita.oligon_kentimata,Gorgon.gorgon, 'προ'),
	new PosotitaBlock(Posotita.apostrofos, 'ος'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon,Chronos.dipli, SecondaryCharacter.rythmos_tetrasimos, 'σε'),
	new PosotitaBlock(Posotita.elafron_apostrofos, 'ει'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'σα'),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon_kato, 'α'),
	new PosotitaBlock(Posotita.ison,SecondaryCharacter.psifiston, 'α'),
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	new PosotitaBlock(Posotita.apostrofos, 'κου'),
	new PosotitaBlock(Posotita.kentimata, 'ου'),
	new PosotitaBlock(Posotita.ison_kentimata,Gorgon.gorgon_parestigmeno, 'σο'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.ison, 'ο'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ον'),
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'μου'),
	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.defteros_teleies),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti_oligon, 'προ'),
	new PosotitaBlock(Posotita.apostrofos, 'ο'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ο'),
	new PosotitaBlock(Posotita.ison,Chronos.klasma, Fthora.chromatiki_skliri_pa, 'σχες'), // TODO fthora kato
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, 'τη'),
	new PosotitaBlock(Posotita.oligon_kentima_kato,Chronos.klasma, 'φω'),
	new PosotitaBlock(Posotita.oligon,SecondaryCharacter.psifiston, 'νη'),
	new PosotitaBlock(Posotita.apostrofos, 'η'),
	new PosotitaBlock(Posotita.apostrofos, 'η'),
	new PosotitaBlock(Posotita.apostrofos, 'η'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'τη'),
	new PosotitaBlock(Posotita.kentimata_oligon,Gorgon.gorgon, 'ης'),
	new PosotitaBlock(Posotita.apostrofos, 'δε'),
	new PosotitaBlock(Posotita.petasti_oligon,Chronos.klasma, 'η'),
	new PosotitaBlock(Posotita.apostrofos_kentimata, 'σε'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'ω'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon, 'ω'),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon, SecondaryCharacter.antikenoma, 'ω'),
	new PosotitaBlock(Posotita.apostrofos, 'ως'),
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'μου'),
	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.defteros_teleies),
	new PosotitaBlock(Posotita.ison, 'εν'),
	new PosotitaBlock(Posotita.ison, 'τω'),
	new PosotitaBlock(Posotita.oligon, 'κε'),
	new PosotitaBlock(Posotita.oligon, 'κρα'),
	new PosotitaBlock(Posotita.oligon_kentimata, 'γε'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos, 'ναι'),
	new PosotitaBlock(Posotita.apostrofos, 'αι'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos, 'με'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ε'),
	new PosotitaBlock(Posotita.oligon, 'ε'),
	new PosotitaBlock(Posotita.oligon_kentimata,Gorgon.gorgon, 'προ'),
	new PosotitaBlock(Posotita.apostrofos, 'ος'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon,Chronos.dipli, SecondaryCharacter.rythmos_tetrasimos, 'σε'),
	SimpleBlock.stavros,
	new PosotitaBlock(Posotita.ison, 'ει'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon, 'σα'),
	new PosotitaBlock(Posotita.ison, 'κου'),
	new PosotitaBlock(Posotita.oligon_apostrofos,Chronos.klasma, SecondaryCharacter.psifiston, 'σο'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon, 'ον'),
	new PosotitaBlock(Posotita.apostrofos,Fthora.chromatiki_malaki_di, 'μου'), // TODO fthora kato
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.ison, 'Κυ'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, Alloiosi.diesi_apli, 'υ'),
	new PosotitaBlock(Posotita.ison,SecondaryCharacter.syndesmos, 'υ'),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon_kato, 'υ'),
	new PosotitaBlock(Posotita.ison, 'υ'),
	new PosotitaBlock(Posotita.kentimata, 'υ'),
	new PosotitaBlock(Posotita.ison_kentimata,Gorgon.gorgon, 'υ'),
	new PosotitaBlock(Posotita.apostrofos, 'υ'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'υ'),
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'ρι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison,Chronos.dipli, SecondaryCharacter.rythmos_tetrasimos, 'ε'),
	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.defteros_teleies),
	AbstractBlock.newline,
);

block_list.push(
	new IchosBlock(Ichos.plagios_protos, Vathmida.pa, Fthora.diatoniki_pa),
	AbstractBlock.newline,
	new PosotitaBlock(Posotita.oligon_ypsili_aristera,Chronos.klasma, Alloiosi.yfesi_apli, SecondaryCharacter.omalon_mono, 'Πα'), // TODO yfesi dexia
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'α'),
	new PosotitaBlock(Posotita.ison,SecondaryCharacter.psifiston, 'α'),
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	new PosotitaBlock(Posotita.apostrofos_kentimata, 'α'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos, 'σα'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.apli, Gorgon.gorgon, 'α'),
	new PosotitaBlock(Posotita.oligon, 'πνο'),
	new PosotitaBlock(Posotita.kentimata, 'ο'),
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, SecondaryCharacter.psifiston, 'η'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'αι'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.ison, 'νε'),
	new PosotitaBlock(Posotita.apostrofos, 'ε'),
	new PosotitaBlock(Posotita.oligon_kentimata,Gorgon.gorgon_parestigmeno, 'σα'), // TODO gorgon thesi
	new PosotitaBlock(Posotita.ison, 'α'),
	new PosotitaBlock(Posotita.petasti_elafron,Chronos.klasma, 'τω'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon, 'ω'),
	new PosotitaBlock(Posotita.oligon, 'τον'),
	new PosotitaBlock(Posotita.oligon, 'Κυ'),
	new PosotitaBlock(Posotita.oligon, 'υ'),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon, SecondaryCharacter.antikenoma, 'υ'),
	new PosotitaBlock(Posotita.apostrofos, 'υ'),
	new PosotitaBlock(Posotita.apostrofos_kentimata,Gorgon.gorgon, 'υ'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'ρι'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon, 'ι'),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon, SecondaryCharacter.antikenoma, 'ι'),
	new PosotitaBlock(Posotita.apostrofos, 'ι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison,Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'ον'),
	new MartyriaBlock(Fthongos.pa, MartyrikoSimadi.alfa),
	new PosotitaBlock(Posotita.ison, 'αι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti_oligon,SecondaryCharacter.rythmos_trisimos, 'νει'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'τε'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon, 'το'),
	new PosotitaBlock(Posotita.kentimata, 'ον'),
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, 'Κυ'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos, 'ρι'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ι'),
	new PosotitaBlock(Posotita.oligon, 'ι'),
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, 'ον'),
	new MartyriaBlock(Fthongos.ke, MartyrikoSimadi.alfa_teleies),
	new PosotitaBlock(Posotita.ison,Gorgon.gorgon, Fthora.chromatiki_skliri_pa, 'εκ'), // TODO fthora kato
	new PosotitaBlock(Posotita.oligon, 'τω'),
	new PosotitaBlock(Posotita.kentimata_oligon,Chronos.apli, SecondaryCharacter.antikenoma, 'ω'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ων'),
	new PosotitaBlock(Posotita.ison_kentimata,Gorgon.gorgon, 'ου'),
	new PosotitaBlock(Posotita.apostrofos, 'ου'),
	new PosotitaBlock(Posotita.syneches_elafron, 'ρα'),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon, SecondaryCharacter.antikenoma, 'α'),
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison,Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'νων'),
	new MartyriaBlock(Fthongos.ke, MartyrikoSimadi.defteros, Fthora.diatoniki_pa),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_kentima_dipla, 'αι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti,SecondaryCharacter.rythmos_trisimos, 'νει'),
	new PosotitaBlock(Posotita.petasti_apostrofos,Chronos.klasma, 'τε'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	new PosotitaBlock(Posotita.apostrofos, 'αυ'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos, 'το'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ο'),
	new PosotitaBlock(Posotita.oligon, 'ον'),
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, 'εν'),
	new PosotitaBlock(Posotita.oligon_kentimata,Gorgon.gorgon, 'τοι'),
	new PosotitaBlock(Posotita.apostrofos, 'οις'),
	new PosotitaBlock(Posotita.oligon_kentimata, 'υ'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'ψι'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon, 'ι'),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon, SecondaryCharacter.antikenoma, 'ι'),
	new PosotitaBlock(Posotita.apostrofos, 'ι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison,Chronos.dipli, SecondaryCharacter.rythmos_tetrasimos, 'στοις'),
	new MartyriaBlock(Fthongos.ke, MartyrikoSimadi.alfa_teleies, Fthora.diatoniki_ke), // TODO fthora position
	new PosotitaBlock(Posotita.oligon_kentima_kato,SecondaryCharacter.antikenoma, 'σοι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, Alloiosi.yfesi_apli, 'πρε'), // NOTE my yfesi
	new PosotitaBlock(Posotita.apostrofos,Chronos.klasma, 'πει'),
	new PosotitaBlock(Posotita.ison, 'υ'),
	new PosotitaBlock(Posotita.kentimata_oligon,Gorgon.gorgon, 'υ'),
	new PosotitaBlock(Posotita.elafron,Chronos.klasma, 'μνος'),
	new PosotitaBlock(Posotita.oligon,Chronos.klasma, Alloiosi.yfesi_apli, SecondaryCharacter.psifiston, 'τω'), // TODO yfesi position
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon, 'ω'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.apostrofos, 'Θε'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ε'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_kentima_dipla,Chronos.dipli, SecondaryCharacter.rythmos_tetrasimos, 'ω'),
	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.delta_teleies),
	AbstractBlock.newline,
);

block_list.push(
	new IchosBlock(Ichos.tetartos, Vathmida.pa, Fthora.diatoniki_pa),
	AbstractBlock.newline,
	new PosotitaBlock(Posotita.petasti_ison,Chronos.klasma, 'Ορ'),
	new PosotitaBlock(Posotita.apostrofos, 'θρο'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon, 'ος'),
	new PosotitaBlock(Posotita.oligon, 'η'),
	new PosotitaBlock(Posotita.kentimata, 'η'),
	new PosotitaBlock(Posotita.petasti, 'η'),
	new PosotitaBlock(Posotita.apostrofos, 'η'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ην'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'βα'),
	new PosotitaBlock(Posotita.yporroi,Gorgon.gorgon, 'α'),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon, SecondaryCharacter.antikenoma, 'α'),
	new PosotitaBlock(Posotita.apostrofos, 'α'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison,Chronos.dipli, SecondaryCharacter.rythmos_tetrasimos, 'θυς'),
	new MartyriaBlock(Fthongos.di_kato, MartyrikoSimadi.delta),
	new PosotitaBlock(Posotita.oligon_ypsili_aristera, 'και'),
	SimpleBlock.stavros,
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison, 'αι'),
	new PosotitaBlock(Posotita.oligon, 'Γυ'),
	new PosotitaBlock(Posotita.petasti,Chronos.klasma, 'ναι'),
	new PosotitaBlock(Posotita.apostrofos,Chronos.apli, SecondaryCharacter.antikenoma, 'κε'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ες'),
	new PosotitaBlock(Posotita.petasti_oligon, 'η'),
	new PosotitaBlock(Posotita.apostrofos, 'η'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'ηλ'),
	new PosotitaBlock(Posotita.ison,Chronos.klasma, 'θον'),
	new MartyriaBlock(Fthongos.vou, MartyrikoSimadi.lambda),
	new PosotitaBlock(Posotita.oligon_kentima_dipla,Gorgon.gorgon_kato, 'ε'),
	new PosotitaBlock(Posotita.ison, 'πι'),
	new PosotitaBlock(Posotita.ison, 'το'),
	new PosotitaBlock(Posotita.petasti, 'μνη'),
	new PosotitaBlock(Posotita.apostrofos, 'η'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.gorgon, 'η'),
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.ison, 'μα'),
	new PosotitaBlock(Posotita.apostrofos,Gorgon.digorgon, 'α'),
	new PosotitaBlock(Posotita.kentimata, 'α'),
	new PosotitaBlock(Posotita.oligon, 'α'),
	new PosotitaBlock(Posotita.ison,Gorgon.gorgon, SecondaryCharacter.omalon_diplo, 'α'),
	new PosotitaBlock(Posotita.apostrofos_kentimata,Gorgon.gorgon, 'σου'),
	new PosotitaBlock(Posotita.apostrofos, 'ου'),
	new PosotitaBlock(Posotita.syneches_elafron, 'Χρι'),
	new PosotitaBlock(Posotita.oligon,Gorgon.gorgon, SecondaryCharacter.antikenoma, 'ι'),
	new PosotitaBlock(Posotita.apostrofos, 'ι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison,Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'στε'),
	new MartyriaBlock(Fthongos.pa, MartyrikoSimadi.alfa),
);

block_list.push(
	new IchosBlock(Ichos.plagios_tetartos, Vathmida.ni, Fthora.diatoniki_ni),
	AbstractBlock.newline,
	new PosotitaBlock(Posotita.oligon_kentima_dipla, 'Κυ'),
	new PosotitaBlock(Posotita.kentimata_oligon, Gorgon.gorgon, 'υ'),
	new PosotitaBlock(Posotita.ison, 'ρι'),
	new PosotitaBlock(Posotita.ison, 'ε'),
	new PosotitaBlock(Posotita.ison, 'ο'),
	new PosotitaBlock(Posotita.kentimata_oligon, Gorgon.gorgon, Alloiosi.yfesi_apli, 'ο'), // TODO yfesi position
	new PosotitaBlock(Posotita.elafron, 'πλον'),
	new PosotitaBlock(Posotita.ison, 'κα'),
	new PosotitaBlock(Posotita.petasti_ison, Fthora.chromatiki_malaki_di, 'τα'), // TODO fthora position
	new PosotitaBlock(Posotita.apostrofos, Alloiosi.diesi_apli, 'του'),
	new PosotitaBlock(Posotita.oligon, 'δι'),
	new PosotitaBlock(Posotita.oligon, 'α'),
	new PosotitaBlock(Posotita.petasti, 'βο'),
	new PosotitaBlock(Posotita.apostrofos, 'ο'),
	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ο'),
	new PosotitaBlock(Posotita.ison, Chronos.klasma, 'λου'),
	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.defteros_teleies),
	new PosotitaBlock(Posotita.ison, Fthora.diatoniki_di, 'τον'),
	new PosotitaBlock(Posotita.ison, 'Σταυ'),
	new PosotitaBlock(Posotita.petasti_ison, 'ρον'),
	new PosotitaBlock(Posotita.apostrofos, 'σου'),
	new PosotitaBlock(Posotita.syneches_elafron, 'η'),
	new PosotitaBlock(Posotita.kentimata, Gorgon.gorgon_kato, 'η'),
	new PosotitaBlock(Posotita.oligon, 'μιν'),
	new PosotitaBlock(Posotita.oligon_apostrofos, SecondaryCharacter.psifiston, 'δε'),
	new PosotitaBlock(Posotita.apostrofos, 'δω'),
	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'κας'),
	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.delta),
	new PosotitaBlock(Posotita.petasti_kentima_ypsili_kentro, Chronos.klasma, 'φριτ'),
	new PosotitaBlock(Posotita.apostrofos, Alloiosi.yfesi_apli, 'τει'), // NOTE my yfesi
	new PosotitaBlock(Posotita.apostrofos, 'ει'),
	new PosotitaBlock(Posotita.apostrofos, 'γαρ'),
	new PosotitaBlock(Posotita.oligon, 'και'),
	new PosotitaBlock(Posotita.oligon_kentimata, SecondaryCharacter.psifiston, 'τρε'),
	new PosotitaBlock(Posotita.apostrofos, Alloiosi.yfesi_apli, 'ε'), // NOTE my yfesi
	new PosotitaBlock(Posotita.apostrofos, 'ε'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'μει'),
	new PosotitaBlock(Posotita.oligon, 'μη'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_apostrofos, SecondaryCharacter.psifiston, 'φε'),
	new PosotitaBlock(Posotita.apostrofos, 'ρων'),
	new PosotitaBlock(Posotita.apostrofos, 'κα'),
	new PosotitaBlock(Posotita.oligon, 'θο'),
	new PosotitaBlock(Posotita.petasti, 'ραν'),
	new PosotitaBlock(Posotita.apostrofos, 'αυ'),
	new PosotitaBlock(Posotita.syneches_elafron, 'του'),
	new PosotitaBlock(Posotita.kentimata, Gorgon.gorgon_kato, 'ου'),
	new PosotitaBlock(Posotita.oligon, 'την'),
	new PosotitaBlock(Posotita.oligon_apostrofos, SecondaryCharacter.psifiston, 'δυ'),
	new PosotitaBlock(Posotita.apostrofos, 'να'),
	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'μιν'),
	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.delta),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.petasti, SecondaryCharacter.rythmos_trisimos, 'ο'),
	new PosotitaBlock(Posotita.apostrofos, 'τι'),
	new PosotitaBlock(Posotita.ison, 'νε'),
	SimpleBlock.diastoli,
	SimpleBlock.vareia,
	new PosotitaBlock(Posotita.ison, 'κρου'),
	new PosotitaBlock(Posotita.apostrofos, Alloiosi.diesi_apli, 'ους'),
	new PosotitaBlock(Posotita.oligon, 'α'),
	new PosotitaBlock(Posotita.oligon, 'νι'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon, Chronos.klasma, SecondaryCharacter.rythmos_trisimos, 'στα'),
	new PosotitaBlock(Posotita.ison, 'και'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.oligon_kentima_kato, SecondaryCharacter.psifiston, Chroa.zygos, 'θα'),
	new PosotitaBlock(Posotita.apostrofos, 'να'),
	new PosotitaBlock(Posotita.apostrofos, 'τον'),
	new PosotitaBlock(Posotita.apostrofos, 'κα'),
	new PosotitaBlock(Posotita.oligon, SecondaryCharacter.psifiston, 'τη'),
	new PosotitaBlock(Posotita.apostrofos, 'ργη'),
	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'σε'),
	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.zygos),
	new PosotitaBlock(Posotita.oligon_kentima_dipla, Fthora.diatoniki_vou, 'δι'),
	new PosotitaBlock(Posotita.oligon, 'α'),
	new PosotitaBlock(Posotita.petasti, 'του'),
	new PosotitaBlock(Posotita.elafron, 'το'),
	new PosotitaBlock(Posotita.oligon, 'προ'),
	new PosotitaBlock(Posotita.oligon, 'σκυ'),
	new PosotitaBlock(Posotita.oligon_kentimata, Gorgon.gorgon, Alloiosi.yfesi_apli, 'νου'), // NOTE my yfesi
	new PosotitaBlock(Posotita.apostrofos, 'ου'),
	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'μεν'),
	new PosotitaBlock(Posotita.ison, 'την'),
	new PosotitaBlock(Posotita.ison, 'τα'),
	new PosotitaBlock(Posotita.ison, SecondaryCharacter.psifiston, 'φην'),
	new PosotitaBlock(Posotita.apostrofos, 'σου'),
	new PosotitaBlock(Posotita.apostrofos, 'και'),
	new PosotitaBlock(Posotita.apostrofos, 'την'),
	new PosotitaBlock(Posotita.oligon_kentima_kato, SecondaryCharacter.psifiston, 'ε'),
	new PosotitaBlock(Posotita.apostrofos, 'ε'),
	new PosotitaBlock(Posotita.apostrofos, Chronos.apli, SecondaryCharacter.antikenoma, 'γε'),
	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ερ'),
	SimpleBlock.diastoli,
	new PosotitaBlock(Posotita.ison, Chronos.dipli, SecondaryCharacter.rythmos_tetrasimos, 'σιν'),
	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.delta),
);
