import { Block } from './block.js';
import { IchosBlock } from './block-ichos.js';
import { PosotitaBlock } from './block-posotita.js';
import { MartyriaBlock } from './block-martyria.js';
import { AgogiBlock } from './block-agogi.js';
import { Ichos } from './ichos.js';
import { Posotita } from './posotita.js';
import { Character } from './character.js';
import { Chronos } from './chronos.js';
import { Gorgon } from './gorgon.js';
import { Alloiosi } from './alloiosi.js';
import { Fthora } from './fthora.js';
import { Chroa } from './chroa.js';
import { Isokratima } from './isokratima.js';
import { Vathmida } from './vathmida.js';
import { Fthongos } from './fthongos.js';
import { MartyrikoSimadi } from './martyriko-simadi.js';
import { Agogi } from './agogi.js';

/**
 * @type {Block[]}
 */
export const block_list = [];

block_list.push(
	new IchosBlock(Ichos.plagios_tetartos, Vathmida.ni, Fthora.diatoniki_ni),
	Block.newline,
	// Εκ νεότητός μου
	PosotitaBlock.build(Posotita.ison, Isokratima.ni, 'Εκ'),
	PosotitaBlock.build(Posotita.ison, 'νε'),
	PosotitaBlock.build(Posotita.oligon_kentima_dipla, 'ο'),
	PosotitaBlock.build(Posotita.oligon, 'τη'),
	PosotitaBlock.build(Posotita.oligon, 'τος'),
	PosotitaBlock.build(Posotita.ison, 'μου'),
	PosotitaBlock.build(Posotita.ison, 'ο'),
	PosotitaBlock.build(Posotita.ison, 'εχ'),
	PosotitaBlock.build(Posotita.apostrofos, Character.vareia, 'θρο'),
	PosotitaBlock.build(Posotita.apostrofos, 'ος'),
	PosotitaBlock.build(Posotita.oligon, 'με'),
	PosotitaBlock.build(Posotita.oligon, 'πει'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Alloiosi.yfesi_apli, 'ρα'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.elafron, 'ζει'),
	PosotitaBlock.build(Posotita.ison, 'ταις'),
	PosotitaBlock.build(Posotita.ison, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, 'δο'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Character.psifiston, Alloiosi.yfesi_apli, 'ναις'),
	PosotitaBlock.build(Posotita.apostrofos, 'φλε'),
	PosotitaBlock.build(Posotita.apostrofos, 'γει'),
	PosotitaBlock.build(Posotita.apostrofos, 'με'),
	PosotitaBlock.build(Posotita.ison, 'ε'),
	PosotitaBlock.build(Posotita.petasti_ison, 'γω'),
	PosotitaBlock.build(Posotita.apostrofos, 'δε'),
	PosotitaBlock.build(Posotita.oligon, 'πε'),
	PosotitaBlock.build(Posotita.oligon, 'ποι'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, 'θως'),
	PosotitaBlock.build(Posotita.ison, 'εν'),
	PosotitaBlock.build(Posotita.oligon, 'σοι'),
	PosotitaBlock.build(Posotita.petasti_apostrofos, 'Κυ'),
	PosotitaBlock.build(Posotita.apostrofos, 'ρι'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'ε'),
	PosotitaBlock.build(Posotita.oligon, 'τρο'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'που'),
	PosotitaBlock.build(Posotita.apostrofos, 'μαι'),
	PosotitaBlock.build(Posotita.apostrofos_kentimata, 'του'),
	PosotitaBlock.build(Posotita.elafron, Chronos.klasma, 'τον'),
	MartyriaBlock.build(Fthongos.ni, MartyrikoSimadi.delta),
	Block.newline,
	// Οι μισούντες Σιών
	PosotitaBlock.build(Posotita.oligon_kentima_dipla, Isokratima.ni, 'Οι'),
	PosotitaBlock.build(Posotita.oligon, 'μι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti, Character.rythmos_trisimos, 'σου'),
	PosotitaBlock.build(Posotita.elafron, 'ντες'),
	PosotitaBlock.build(Posotita.oligon, 'Σι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, 'ων'),
	PosotitaBlock.build(Posotita.ison, 'γε'),
	PosotitaBlock.build(Posotita.ison, 'νη'),
	PosotitaBlock.build(Posotita.ison, 'θη'),
	PosotitaBlock.build(Posotita.kentimata, 'η'),
	PosotitaBlock.build(Posotita.ison, 'τω'),
	PosotitaBlock.build(Posotita.elafron, 'σαν'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, 'δη'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Character.rythmos_trisimos, 'πριν'),
	PosotitaBlock.build(Posotita.ison, 'εκ'),
	PosotitaBlock.build(Posotita.ison, 'σπα'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.elafron_apostrofos, 'σθη'),
	PosotitaBlock.build(Posotita.kentimata, 'η'),
	PosotitaBlock.build(Posotita.ison, 'ναι'),
	PosotitaBlock.build(Posotita.elafron, 'ως'),
	PosotitaBlock.build(Posotita.oligon_kentimata, 'χορ'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.elafron, Chronos.klasma, Character.rythmos_trisimos, 'τος'),
	PosotitaBlock.build(Posotita.oligon, 'συγ'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti, 'κο'),
	PosotitaBlock.build(Posotita.apostrofos, 'ψει'),
	PosotitaBlock.build(Posotita.oligon, 'γαρ'),
	PosotitaBlock.build(Posotita.oligon, 'Χρι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Character.rythmos_trisimos, 'στος'),
	Block.stavros,
	PosotitaBlock.build(Posotita.ison, 'αυ'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon, Alloiosi.yfesi_apli, 'χε'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.apostrofos, 'ε'),
	PosotitaBlock.build(Posotita.apostrofos, 'νας'),
	PosotitaBlock.build(Posotita.ison, 'αυ'),
	PosotitaBlock.build(Posotita.elafron_apostrofos, 'των'),
	PosotitaBlock.build(Posotita.oligon, 'το'),
	PosotitaBlock.build(Posotita.ison, 'μη'),
	PosotitaBlock.build(Posotita.elafron, 'βα'),
	PosotitaBlock.build(Posotita.oligon_kentimata, 'σα'),
	PosotitaBlock.build(Posotita.elafron, Chronos.klasma, 'νων'),
	MartyriaBlock.build(Fthongos.ni, MartyrikoSimadi.delta),
	Block.newline,
	// Δόξα, Και νυν
	Block.diastoli,
	new AgogiBlock(Agogi.tacheia),
	PosotitaBlock.build(Posotita.oligon_ypsili_dexia, Isokratima.ni, Character.rythmos_trisimos, 'Δο'),
	PosotitaBlock.build(Posotita.ison, 'ξα'),
	PosotitaBlock.build(Posotita.ison, 'Πα'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_ison, Character.rythmos_trisimos, 'τρι'),
	PosotitaBlock.build(Posotita.ison, 'και'),
	PosotitaBlock.build(Posotita.ison, 'Υι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_ison, Character.rythmos_trisimos, 'ω'),
	PosotitaBlock.build(Posotita.ison, 'και'),
	PosotitaBlock.build(Posotita.ison, 'Α'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.apostrofos, 'γι'),
	PosotitaBlock.build(Posotita.oligon, 'ω'),
	PosotitaBlock.build(Posotita.petasti, 'Πνευ'),
	PosotitaBlock.build(Posotita.apostrofos, 'μα'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, Character.rythmos_trisimos, 'τι'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies),
	PosotitaBlock.build(Posotita.chamili, 'και'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_ypsili_dexia, Character.rythmos_trisimos, 'νυν'),
	PosotitaBlock.build(Posotita.ison, 'και'),
	PosotitaBlock.build(Posotita.ison, 'α'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti, Character.rythmos_trisimos, 'ει'),
	PosotitaBlock.build(Posotita.apostrofos, 'και'),
	PosotitaBlock.build(Posotita.ison, 'εις'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, 'τους'),
	PosotitaBlock.build(Posotita.ison, 'αι'),
	new AgogiBlock(Agogi.metria),
	PosotitaBlock.build(Posotita.ison, Character.psifiston, 'ω'),
	PosotitaBlock.build(Posotita.apostrofos, 'νας'),
	PosotitaBlock.build(Posotita.apostrofos, 'των'),
	PosotitaBlock.build(Posotita.apostrofos, 'αι'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Character.psifiston, 'ω'),
	PosotitaBlock.build(Posotita.apostrofos, 'νων'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, Character.rythmos_trisimos, 'μην'), // TODO rythmos on klasma
	MartyriaBlock.build(Fthongos.ni, MartyrikoSimadi.delta),
	Block.newline,
	// Αγίω Πνεύματι
	PosotitaBlock.build(Posotita.ison, Isokratima.ni, 'Α'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentima_dipla, 'γι'),
	PosotitaBlock.build(Posotita.oligon, 'ω'),
	PosotitaBlock.build(Posotita.oligon, 'Πνευ'),
	PosotitaBlock.build(Posotita.ison, 'μα'),
	PosotitaBlock.build(Posotita.ison, 'τι'),
	PosotitaBlock.build(Posotita.ison, 'το'),
	PosotitaBlock.build(Posotita.petasti, 'ζην'),
	PosotitaBlock.build(Posotita.apostrofos, 'τα'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentimata, Alloiosi.yfesi_apli, Character.rythmos_trisimos, 'παν'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.elafron, 'τα'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti, Character.rythmos_trisimos, 'φως'),
	PosotitaBlock.build(Posotita.apostrofos, 'εκ'),
	PosotitaBlock.build(Posotita.ison, 'φω'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.apostrofos, Character.vareia, 'το'),
	PosotitaBlock.build(Posotita.apostrofos, 'ος'),
	PosotitaBlock.build(Posotita.oligon, 'Θε'),
	PosotitaBlock.build(Posotita.oligon, 'ος'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Alloiosi.yfesi_apli, 'με'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.elafron, Chronos.klasma, 'γας'),
	PosotitaBlock.build(Posotita.ison, 'συν'),
	PosotitaBlock.build(Posotita.oligon, 'Πα'),
	PosotitaBlock.build(Posotita.petasti, Alloiosi.yfesi_apli, 'τρι'), // NOTE my yfesi
	Block.stavros,
	PosotitaBlock.build(Posotita.elafron, 'υ'),
	PosotitaBlock.build(Posotita.oligon, Character.vareia, 'μνου'),
	PosotitaBlock.build(Posotita.ison, Character.omalon_diplo, 'ου'),
	PosotitaBlock.build(Posotita.apostrofos, 'μεν'),
	PosotitaBlock.build(Posotita.ison, 'αυ'),
	PosotitaBlock.build(Posotita.elafron_apostrofos, 'το'),
	PosotitaBlock.build(Posotita.kentimata, 'ο'),
	PosotitaBlock.build(Posotita.ison, 'και'),
	PosotitaBlock.build(Posotita.elafron, 'τω'),
	PosotitaBlock.build(Posotita.oligon_kentimata, 'Λο'),
	PosotitaBlock.build(Posotita.elafron, Chronos.klasma, 'γω'),
	MartyriaBlock.build(Fthongos.ni, MartyrikoSimadi.delta),
	Block.newline,
);

block_list.push(
	new IchosBlock(Ichos.protos, Vathmida.pa, Fthora.diatoniki_pa),
	Block.newline,
	PosotitaBlock.build(Posotita.petasti, Isokratima.pa, 'Κυ'),
	PosotitaBlock.build(Posotita.apostrofos, 'ρι'),
	PosotitaBlock.build(Posotita.ison, 'ε'),
	Block.stavros,
	PosotitaBlock.build(Posotita.oligon, 'ε'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Character.psifiston, 'κε'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'κρα'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.apli, Character.antikenoma, 'ξα'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, Isokratima.melos, 'α'),
	PosotitaBlock.build(Posotita.ison, Character.vareia, 'προ'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ο'),
	PosotitaBlock.build(Posotita.oligon, 'ος'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti_oligon, Character.rythmos_tetrasimos, 'σε'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'ε'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	PosotitaBlock.build(Posotita.ison, Isokratima.pa, 'ει'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti_kentima, Chronos.klasma, 'σα'),
	PosotitaBlock.build(Posotita.apostrofos_kentimata, 'κου'),
	PosotitaBlock.build(Posotita.apostrofos_yporroi, Chronos.klasma, Gorgon.gorgon, 'σο'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ο'),
	PosotitaBlock.build(Posotita.apostrofos, 'ον'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'μου'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon_kato, 'ει'),
	PosotitaBlock.build(Posotita.oligon, 'σα'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, Alloiosi.yfesi_apli, 'α'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'κου'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.apli, Gorgon.gorgon, 'ου'),
	PosotitaBlock.build(Posotita.ison_kentimata, Gorgon.gorgon, 'σο'),
	PosotitaBlock.build(Posotita.apostrofos, 'ον'),
	PosotitaBlock.build(Posotita.apostrofos, Character.vareia, Isokratima.melos, 'μου'),
	PosotitaBlock.build(Posotita.apostrofos, 'ου'),
	PosotitaBlock.build(Posotita.oligon, 'Κυ'),
	PosotitaBlock.build(Posotita.kentimata_oligon, Isokratima.pa, 'υ'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon, 'υ'),
	PosotitaBlock.build(Posotita.apostrofos_yporroi, Chronos.klasma, Gorgon.gorgon, Character.vareia, 'ρι'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ι'),
	PosotitaBlock.build(Posotita.apostrofos, 'ι'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'ε'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	PosotitaBlock.build(Posotita.petasti_kentima, 'Κυ'),
	PosotitaBlock.build(Posotita.apostrofos, 'ρι'),
	PosotitaBlock.build(Posotita.ison, 'ε'),
	Block.stavros,
	PosotitaBlock.build(Posotita.oligon, 'ε'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Character.psifiston, Alloiosi.yfesi_apli, 'κε'),
	PosotitaBlock.build(Posotita.apostrofos, 'κρα'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.petasti_apostrofos, Chronos.klasma, 'ξα'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'προ'),
	PosotitaBlock.build(Posotita.kentimata, 'ος'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon, 'σε'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'ε'),
	MartyriaBlock.build(Fthongos.ga, MartyrikoSimadi.nana),
	PosotitaBlock.build(Posotita.elafron, 'ει'),
	PosotitaBlock.build(Posotita.ison, 'σα'),
	PosotitaBlock.build(Posotita.ison, 'κου'),
	PosotitaBlock.build(Posotita.oligon_kentima_kato, Chronos.klasma, Isokratima.zo, Character.psifiston, 'σο'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.gorgon, 'ο'),
	PosotitaBlock.build(Posotita.apostrofos, 'ο'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ον'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Character.vareia, Character.rythmos_trisimos, 'μου'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.digorgon, 'ου'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, 'ου'),
	MartyriaBlock.build(Fthongos.zo, MartyrikoSimadi.varys),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_ypsili_aristera, Chronos.klasma, Isokratima.pa, Character.omalon_mono, 'προ'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'σχες'),
	PosotitaBlock.build(Posotita.ison, 'τη'),
	PosotitaBlock.build(Posotita.apostrofos, 'φω'),
	PosotitaBlock.build(Posotita.oligon, 'νη'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'η'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.gorgon, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, Character.vareia, Isokratima.melos, 'τη'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'η'),
	PosotitaBlock.build(Posotita.oligon, 'ης'),
	Block.stavros,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Isokratima.pa, 'δε'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, 'η'),
	PosotitaBlock.build(Posotita.oligon_kentimata, 'σε'),
	PosotitaBlock.build(Posotita.apostrofos_yporroi, Chronos.klasma, Gorgon.gorgon, Character.vareia, 'ω'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ω'),
	PosotitaBlock.build(Posotita.apostrofos, 'ως'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'μου'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	PosotitaBlock.build(Posotita.oligon_kentima_dipla, 'εν'),
	PosotitaBlock.build(Posotita.ison, 'τω'),
	PosotitaBlock.build(Posotita.apostrofos, 'κε'),
	PosotitaBlock.build(Posotita.oligon, 'κρα'),
	PosotitaBlock.build(Posotita.oligon_ypsili_dexia, Chronos.klasma, Isokratima.di, Character.psifiston, 'γε'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'ναι'), // TODO enarmonia fthora
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, Isokratima.pa, 'με'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.apli, Character.antikenoma, 'προ'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ος'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentima_kato, Character.vareia, Character.rythmos_tetrasimos, 'σε'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.trigorgon, 'ε'),
	PosotitaBlock.build(Posotita.apostrofos, 'ε'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon, 'ε'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'ε'),
	MartyriaBlock.build(Fthongos.ga, MartyrikoSimadi.nana, Fthora.diatoniki_ga),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon_kato, 'ει'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentimata, 'σα'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'κου'),
	PosotitaBlock.build(Posotita.apostrofos_kentimata, Gorgon.gorgon, 'σο'),
	PosotitaBlock.build(Posotita.apostrofos, 'ον'),
	PosotitaBlock.build(Posotita.syneches_elafron, Chronos.klasma, 'μου'),
	PosotitaBlock.build(Posotita.oligon, 'Κυ'),
	PosotitaBlock.build(Posotita.kentimata, 'υ'),
	PosotitaBlock.build(Posotita.petasti, Chronos.klasma, Character.psifiston, 'υ'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'υ'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, Character.vareia, 'ρι'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.gorgon, 'ι'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ι'),
	PosotitaBlock.build(Posotita.apostrofos, 'ι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'ε'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	Block.newline,
);

block_list.push(
	new IchosBlock(Ichos.protos, Vathmida.pa, Fthora.diatoniki_pa),
	Block.newline,
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentima, Isokratima.pa, Character.rythmos_trisimos, 'Δευ'), // TODO isokratima position
	PosotitaBlock.build(Posotita.ison, 'τε'),
	PosotitaBlock.build(Posotita.apostrofos, 'λα'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, 'οι'),
	PosotitaBlock.build(Posotita.oligon, 'υ'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, Alloiosi.yfesi_apli, 'μνη'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.apostrofos, 'σω'),
	PosotitaBlock.build(Posotita.apostrofos, 'μεν'),
	PosotitaBlock.build(Posotita.ison, 'και'),
	PosotitaBlock.build(Posotita.ison, 'προ'),
	PosotitaBlock.build(Posotita.ison, 'σκυ'),
	PosotitaBlock.build(Posotita.apostrofos, 'νη'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'σω'),
	PosotitaBlock.build(Posotita.oligon, 'μεν'),
	PosotitaBlock.build(Posotita.oligon, 'Χρι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Character.rythmos_trisimos, 'στον'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies),
	PosotitaBlock.build(Posotita.ison, 'δο'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, 'ξα'),
	PosotitaBlock.build(Posotita.ison, 'ζο'),
	PosotitaBlock.build(Posotita.apostrofos, 'ντες'),
	PosotitaBlock.build(Posotita.apostrofos, 'αυ'),
	PosotitaBlock.build(Posotita.oligon, 'του'),
	PosotitaBlock.build(Posotita.ison, 'την'),
	PosotitaBlock.build(Posotita.apostrofos, 'εκ'),
	PosotitaBlock.build(Posotita.apostrofos, 'νε'),
	PosotitaBlock.build(Posotita.oligon, 'κρων'),
	PosotitaBlock.build(Posotita.oligon, 'α'),
	PosotitaBlock.build(Posotita.ison, Character.psifiston, 'να'),
	PosotitaBlock.build(Posotita.apostrofos, 'στα'),
	PosotitaBlock.build(Posotita.syneches_elafron, Chronos.klasma, 'σιν'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti_ypsili_dexia, Character.rythmos_trisimos, 'ο'),
	PosotitaBlock.build(Posotita.elafron, 'τι'),
	PosotitaBlock.build(Posotita.oligon, 'αυ'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, 'τος'),
	PosotitaBlock.build(Posotita.ison, 'ε'),
	PosotitaBlock.build(Posotita.ison, Character.vareia, 'στι'),
	PosotitaBlock.build(Posotita.apostrofos, 'ιν'),
	PosotitaBlock.build(Posotita.oligon, 'ο'),
	PosotitaBlock.build(Posotita.ison, 'Θε'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, Alloiosi.yfesi_apli, 'ος'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.apostrofos, 'η'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, Character.rythmos_trisimos, 'μων'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies),
	PosotitaBlock.build(Posotita.elafron_apostrofos, Fthora.chromatiki_skliri_pa, 'ο'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, 'εκ'),
	PosotitaBlock.build(Posotita.oligon, 'της'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'πλα'),
	PosotitaBlock.build(Posotita.apostrofos, 'νης'),
	PosotitaBlock.build(Posotita.apostrofos, 'του'),
	PosotitaBlock.build(Posotita.oligon, 'εχ'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Character.rythmos_trisimos, 'θρου'),
	PosotitaBlock.build(Posotita.ison, Fthora.diatoniki_di, 'τον'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti_ison, 'κο'),
	PosotitaBlock.build(Posotita.apostrofos, 'σμον'),
	PosotitaBlock.build(Posotita.ison, 'λυ'),
	PosotitaBlock.build(Posotita.apostrofos, 'τρω'),
	PosotitaBlock.build(Posotita.oligon_kentima_kato, Character.psifiston, 'σα'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.apli, Character.antikenoma, 'με'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ε'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'νος'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	Block.newline,
	new AgogiBlock(Agogi.tacheia),
	PosotitaBlock.build(Posotita.ison, Isokratima.pa, 'Γε'),
	PosotitaBlock.build(Posotita.ison, Gorgon.gorgon_kato, 'νη'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentima, Character.rythmos_trisimos, 'θη'),
	PosotitaBlock.build(Posotita.ison, 'τω'),
	PosotitaBlock.build(Posotita.ison, 'τα'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_ison, 'ω'),
	PosotitaBlock.build(Posotita.ison, 'τα'),
	PosotitaBlock.build(Posotita.ison, 'σου'),
	PosotitaBlock.build(Posotita.ison, 'προ'),
	PosotitaBlock.build(Posotita.petasti, 'σε'),
	PosotitaBlock.build(Posotita.apostrofos, 'χο'),
	PosotitaBlock.build(Posotita.ison, 'ντα'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies),
	PosotitaBlock.build(Posotita.apostrofos, 'εις'),
	PosotitaBlock.build(Posotita.apostrofos, 'την'),
	PosotitaBlock.build(Posotita.oligon, 'φω'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, 'νην'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies, Agogi.metria),
	PosotitaBlock.build(Posotita.petasti_ison, 'της'),
	PosotitaBlock.build(Posotita.apostrofos, 'δε'),
	PosotitaBlock.build(Posotita.petasti_ison, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, 'σε'),
	PosotitaBlock.build(Posotita.oligon_kentimata, 'ως'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, Chronos.rythmos_trisimos, 'μου'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies),
	Block.newline,
	PosotitaBlock.build(Posotita.ison, Isokratima.pa, 'Ευ'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti, Chronos.klasma, 'φρα'),
	PosotitaBlock.build(Posotita.apostrofos, 'νθη'),
	PosotitaBlock.build(Posotita.apostrofos, 'τε'),
	PosotitaBlock.build(Posotita.apostrofos, 'ου'),
	PosotitaBlock.build(Posotita.oligon, 'ρα'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Isokratima.di, Character.rythmos_trisimos, 'νοι'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies),
	PosotitaBlock.build(Posotita.ison, 'σαλ'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentima, Character.psifiston, 'πι'),
	PosotitaBlock.build(Posotita.apostrofos, Alloiosi.yfesi_apli, 'ι'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.apostrofos, 'σα'),
	PosotitaBlock.build(Posotita.apostrofos, 'τε'),
	PosotitaBlock.build(Posotita.ison, Isokratima.pa, 'τα'),
	PosotitaBlock.build(Posotita.apostrofos, 'θε'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'με'),
	PosotitaBlock.build(Posotita.apostrofos, 'λι'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.oligon, 'της'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Isokratima.di, Character.rythmos_trisimos, 'γης'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies),
	PosotitaBlock.build(Posotita.ison, 'βο'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti_kentima, Chronos.klasma, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, Alloiosi.yfesi_apli, 'σα'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, Isokratima.pa, 'τε'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'τα'),
	PosotitaBlock.build(Posotita.oligon_kentima_dipla, 'ο'),
	PosotitaBlock.build(Posotita.ison, 'ρη'),
	PosotitaBlock.build(Posotita.ison, 'ευ'),
	PosotitaBlock.build(Posotita.apostrofos, 'φρο'),
	PosotitaBlock.build(Posotita.ison, Character.psifiston, 'συ'),
	PosotitaBlock.build(Posotita.apostrofos, 'υ'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'νην'),
	PosotitaBlock.build(Posotita.oligon_kentima, 'ι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'δου'),
	PosotitaBlock.build(Posotita.apostrofos, 'γαρ'),
	PosotitaBlock.build(Posotita.apostrofos, 'ο'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'Εμ'),
	PosotitaBlock.build(Posotita.oligon, 'μα'),
	PosotitaBlock.build(Posotita.oligon, 'νου'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Character.rythmos_trisimos, 'ηλ'),
	PosotitaBlock.build(Posotita.elafron_apostrofos, Isokratima.melos, 'τας'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, 'α'),
	PosotitaBlock.build(Posotita.ison, 'μαρ'),
	PosotitaBlock.build(Posotita.petasti_ison, Chronos.klasma, Fthora.chromatiki_skliri_di, 'τι'), // TODO fthora position, fthongos hint
	PosotitaBlock.build(Posotita.syneches_elafron, 'ας'),
	PosotitaBlock.build(Posotita.oligon, 'η'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Isokratima.pa, 'μων'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.skliro),
	PosotitaBlock.build(Posotita.oligon_kentima, Fthora.diatoniki_di, 'τω'), // TODO fthora position, pitch change
	PosotitaBlock.build(Posotita.ison, 'σταυ'),
	PosotitaBlock.build(Posotita.petasti_ison, 'ρω'),
	PosotitaBlock.build(Posotita.apostrofos, 'προ'),
	PosotitaBlock.build(Posotita.ison, Character.psifiston, 'ση'),
	PosotitaBlock.build(Posotita.apostrofos, 'λω'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'σε'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	PosotitaBlock.build(Posotita.oligon, 'και'),
	PosotitaBlock.build(Posotita.oligon, 'ζω'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti, Character.rythmos_trisimos, 'ην'),
	PosotitaBlock.build(Posotita.elafron, 'ο'),
	PosotitaBlock.build(Posotita.oligon, 'δι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, 'δους'),
	PosotitaBlock.build(Posotita.petasti_ison, 'θα'),
	PosotitaBlock.build(Posotita.apostrofos, 'να'),
	PosotitaBlock.build(Posotita.syneches_elafron, Chronos.klasma, Isokratima.melos, 'τον'),
	PosotitaBlock.build(Posotita.ison, Gorgon.gorgon_kato, 'ε'),
	PosotitaBlock.build(Posotita.ison_kentimata, Gorgon.gorgon, 'νε'),
	PosotitaBlock.build(Posotita.apostrofos, 'κρω'),
	PosotitaBlock.build(Posotita.syneches_elafron, Chronos.klasma, 'σε'),
	MartyriaBlock.build(Fthongos.zo, MartyrikoSimadi.varys),
	PosotitaBlock.build(Posotita.oligon_ypsili_dexia, Isokratima.pa, 'τον'),
	PosotitaBlock.build(Posotita.oligon, 'Α'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, Character.rythmos_trisimos, 'δαμ'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, 'να'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti, 'στη'),
	PosotitaBlock.build(Posotita.apostrofos, 'σας'),
	PosotitaBlock.build(Posotita.ison, 'ως'),
	PosotitaBlock.build(Posotita.apostrofos, 'φι'),
	PosotitaBlock.build(Posotita.oligon_kentima_kato, Character.psifiston, 'λα'),
	PosotitaBlock.build(Posotita.apostrofos, 'αν'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.apli, Character.antikenoma, 'θρω'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ω'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'πος'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	Block.newline,
);

block_list.push(
	new IchosBlock(Ichos.defteros, Vathmida.di, Fthora.chromatiki_malaki_di),
	Block.newline,
	PosotitaBlock.build(Posotita.elafron, Isokratima.melos, 'Κυ'),
	PosotitaBlock.build(Posotita.kentimata_oligon, Isokratima.di, 'υ'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon, 'υ'),
	PosotitaBlock.build(Posotita.elafron, Chronos.klasma, 'ρι'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'ε'),
	Block.stavros,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, 'ε'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Character.psifiston, 'κε'),
	PosotitaBlock.build(Posotita.apostrofos, 'κρα'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.petasti_apostrofos, Chronos.klasma, 'ξα'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'προ'),
	PosotitaBlock.build(Posotita.kentimata, 'ος'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.dipli, 'σε'),
	PosotitaBlock.build(Posotita.apostrofos, 'ει'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentimata, Character.psifiston, 'σα'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'κου'),
	PosotitaBlock.build(Posotita.oligon_kentima, Chronos.apli, Character.antikenoma, 'σο'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ο'),
	PosotitaBlock.build(Posotita.ison_kentimata, Gorgon.gorgon_meta, 'ο'),
	PosotitaBlock.build(Posotita.ison, Character.vareia, 'ο'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ον'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'μου'),
	PosotitaBlock.build(Posotita.ison, 'ει'),
	PosotitaBlock.build(Posotita.kentimata, 'ει'),
	PosotitaBlock.build(Posotita.oligon_kentimata, 'σα'),
	PosotitaBlock.build(Posotita.apostrofos, 'κου'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'ου'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.gorgon, 'ου'),
	PosotitaBlock.build(Posotita.apostrofos, 'ου'),
	PosotitaBlock.build(Posotita.petasti, 'σον'),
	PosotitaBlock.build(Posotita.elafron, 'μου'),
	PosotitaBlock.build(Posotita.ison, 'Κυ'),
	PosotitaBlock.build(Posotita.kentimata, 'υ'),
	PosotitaBlock.build(Posotita.ison_kentimata, 'υ'),
	PosotitaBlock.build(Posotita.apostrofos_yporroi, Chronos.klasma, Gorgon.gorgon, Character.vareia, 'ρι'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ι'),
	PosotitaBlock.build(Posotita.apostrofos, 'ι'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'ε'),
	MartyriaBlock.build(Fthongos.vou, MartyrikoSimadi.defteros_teleies),
	PosotitaBlock.build(Posotita.oligon_ypsili_aristera, Character.psifiston, 'Κυ'),
	PosotitaBlock.build(Posotita.apostrofos, 'υ'),
	PosotitaBlock.build(Posotita.elafron_kentimata, Gorgon.gorgon_meta, 'ρι'),
	PosotitaBlock.build(Posotita.ison, Character.vareia, 'ι'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ι'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'ε'),
	PosotitaBlock.build(Posotita.ison, Gorgon.gorgon_kato, 'ε'),
	PosotitaBlock.build(Posotita.oligon_kentima, 'κε'),
	PosotitaBlock.build(Posotita.oligon, 'ε'),
	PosotitaBlock.build(Posotita.apostrofos, Character.vareia, 'κρα'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, Character.vareia, 'ξα'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'α'),
	PosotitaBlock.build(Posotita.oligon, 'α'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon, 'προ'),
	PosotitaBlock.build(Posotita.apostrofos, 'ος'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.dipli, Character.rythmos_tetrasimos, 'σε'),
	PosotitaBlock.build(Posotita.elafron_apostrofos, 'ει'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'σα'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon_kato, 'α'),
	PosotitaBlock.build(Posotita.ison, Character.psifiston, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, 'κου'),
	PosotitaBlock.build(Posotita.kentimata, 'ου'),
	PosotitaBlock.build(Posotita.ison_kentimata, Gorgon.gorgon_meta, 'σο'),
	PosotitaBlock.build(Posotita.ison, Character.vareia, 'ο'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ον'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'μου'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.defteros_teleies),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti_oligon, 'προ'),
	PosotitaBlock.build(Posotita.apostrofos, 'ο'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ο'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, Fthora.chromatiki_skliri_pa, 'σχες'), // TODO fthora kato
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, 'τη'),
	PosotitaBlock.build(Posotita.oligon_kentima_kato, Chronos.klasma, 'φω'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'νη'),
	PosotitaBlock.build(Posotita.apostrofos, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'τη'),
	PosotitaBlock.build(Posotita.kentimata_oligon, Gorgon.gorgon, 'ης'),
	PosotitaBlock.build(Posotita.apostrofos, 'δε'),
	PosotitaBlock.build(Posotita.petasti_oligon, Chronos.klasma, 'η'),
	PosotitaBlock.build(Posotita.apostrofos_kentimata, 'σε'),
	PosotitaBlock.build(Posotita.apostrofos_yporroi, Chronos.klasma, Gorgon.gorgon, Character.vareia, 'ω'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ω'),
	PosotitaBlock.build(Posotita.apostrofos, 'ως'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'μου'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.defteros_teleies),
	PosotitaBlock.build(Posotita.ison, 'εν'),
	PosotitaBlock.build(Posotita.ison, 'τω'),
	PosotitaBlock.build(Posotita.oligon, 'κε'),
	PosotitaBlock.build(Posotita.oligon, 'κρα'),
	PosotitaBlock.build(Posotita.oligon_kentimata, 'γε'),
	PosotitaBlock.build(Posotita.apostrofos, Character.vareia, 'ναι'),
	PosotitaBlock.build(Posotita.apostrofos, 'αι'),
	PosotitaBlock.build(Posotita.apostrofos, Character.vareia, 'με'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ε'),
	PosotitaBlock.build(Posotita.oligon, 'ε'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon, 'προ'),
	PosotitaBlock.build(Posotita.apostrofos, 'ος'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.dipli, Character.rythmos_tetrasimos, 'σε'),
	Block.stavros,
	PosotitaBlock.build(Posotita.ison, 'ει'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, 'σα'),
	PosotitaBlock.build(Posotita.ison, 'κου'),
	PosotitaBlock.build(Posotita.oligon_apostrofos, Chronos.klasma, Character.psifiston, 'σο'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.gorgon, 'ον'),
	PosotitaBlock.build(Posotita.apostrofos, Fthora.chromatiki_malaki_di, 'μου'), // TODO fthora kato
	PosotitaBlock.build(Posotita.ison, Character.vareia, 'Κυ'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, Alloiosi.diesi_apli, 'υ'),
	PosotitaBlock.build(Posotita.ison, Character.syndesmos, 'υ'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon_kato, 'υ'),
	PosotitaBlock.build(Posotita.ison, 'υ'),
	PosotitaBlock.build(Posotita.kentimata, 'υ'),
	PosotitaBlock.build(Posotita.ison_kentimata, Gorgon.gorgon, 'υ'),
	PosotitaBlock.build(Posotita.apostrofos, 'υ'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'υ'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'ρι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'ε'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.defteros_teleies),
	Block.newline,
);

block_list.push(
	new IchosBlock(Ichos.plagios_protos, Vathmida.pa, Fthora.diatoniki_pa),
	Block.newline,
	PosotitaBlock.build(Posotita.oligon_ypsili_aristera, Chronos.klasma, Alloiosi.yfesi_apli, Isokratima.pa, Character.omalon_mono, 'Πα'), // TODO yfesi and isokratima to the right
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'α'),
	PosotitaBlock.build(Posotita.ison, Character.psifiston, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.apostrofos_kentimata, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, Character.vareia, 'σα'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.apli, Gorgon.gorgon, 'α'),
	PosotitaBlock.build(Posotita.oligon, 'πνο'),
	PosotitaBlock.build(Posotita.kentimata, 'ο'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Character.psifiston, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'αι'),
	PosotitaBlock.build(Posotita.ison, Character.vareia, 'νε'),
	PosotitaBlock.build(Posotita.apostrofos, 'ε'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon_meta, 'σα'),
	PosotitaBlock.build(Posotita.ison, 'α'),
	PosotitaBlock.build(Posotita.petasti_elafron, Chronos.klasma, 'τω'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.gorgon, 'ω'),
	PosotitaBlock.build(Posotita.oligon, 'τον'),
	PosotitaBlock.build(Posotita.oligon, 'Κυ'),
	PosotitaBlock.build(Posotita.oligon, 'υ'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'υ'),
	PosotitaBlock.build(Posotita.apostrofos, 'υ'),
	PosotitaBlock.build(Posotita.apostrofos_kentimata, Gorgon.gorgon, 'υ'),
	PosotitaBlock.build(Posotita.apostrofos_yporroi, Chronos.klasma, Gorgon.gorgon, Character.vareia, 'ρι'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ι'),
	PosotitaBlock.build(Posotita.apostrofos, 'ι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, Character.rythmos_trisimos, 'ον'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	PosotitaBlock.build(Posotita.ison, 'αι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti_oligon, Character.rythmos_trisimos, 'νει'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'τε'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, 'το'),
	PosotitaBlock.build(Posotita.kentimata, 'ον'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, 'Κυ'),
	PosotitaBlock.build(Posotita.apostrofos, Character.vareia, 'ρι'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ι'),
	PosotitaBlock.build(Posotita.oligon, 'ι'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Isokratima.ke, 'ον'),
	MartyriaBlock.build(Fthongos.ke, MartyrikoSimadi.alfa_teleies),
	PosotitaBlock.build(Posotita.ison, Gorgon.gorgon, Fthora.chromatiki_skliri_pa, 'εκ'), // TODO fthora kato
	PosotitaBlock.build(Posotita.oligon, 'τω'),
	PosotitaBlock.build(Posotita.kentimata_oligon, Chronos.apli, Character.antikenoma, 'ω'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ων'),
	PosotitaBlock.build(Posotita.ison_kentimata, Gorgon.gorgon, 'ου'),
	PosotitaBlock.build(Posotita.apostrofos, 'ου'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'ρα'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, Character.rythmos_trisimos, 'νων'),
	MartyriaBlock.build(Fthongos.ke, MartyrikoSimadi.defteros, Fthora.diatoniki_pa),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentima_dipla, 'αι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti, Character.rythmos_trisimos, 'νει'),
	PosotitaBlock.build(Posotita.petasti_apostrofos, Chronos.klasma, 'τε'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, 'αυ'),
	PosotitaBlock.build(Posotita.apostrofos, Character.vareia, Isokratima.melos, 'το'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ο'),
	PosotitaBlock.build(Posotita.oligon, 'ον'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Isokratima.ke, 'εν'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon, 'τοι'),
	PosotitaBlock.build(Posotita.apostrofos, 'οις'),
	PosotitaBlock.build(Posotita.oligon_kentimata, 'υ'),
	PosotitaBlock.build(Posotita.apostrofos_yporroi, Chronos.klasma, Gorgon.gorgon, Character.vareia, 'ψι'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ι'),
	PosotitaBlock.build(Posotita.apostrofos, 'ι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'στοις'),
	MartyriaBlock.build(Fthongos.ke, MartyrikoSimadi.alfa_teleies, Fthora.diatoniki_ke),
	PosotitaBlock.build(Posotita.oligon_kentima_kato, Character.antikenoma, 'σοι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, Alloiosi.yfesi_apli, 'πρε'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'πει'),
	PosotitaBlock.build(Posotita.ison, 'υ'),
	PosotitaBlock.build(Posotita.kentimata_oligon, Gorgon.gorgon, 'υ'),
	PosotitaBlock.build(Posotita.elafron, Chronos.klasma, 'μνος'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Alloiosi.yfesi_apli, Isokratima.di, Character.psifiston, 'τω'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.gorgon, 'ω'),
	PosotitaBlock.build(Posotita.apostrofos, Character.vareia, 'Θε'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ε'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentima_dipla, Chronos.dipli, Isokratima.pa, Character.rythmos_tetrasimos, 'ω'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies),
	Block.newline,
);

block_list.push(
	new IchosBlock(Ichos.tetartos, Vathmida.pa, Fthora.diatoniki_pa),
	Block.newline,
	PosotitaBlock.build(Posotita.petasti_ison, Chronos.klasma, Isokratima.melos, 'Ορ'),
	PosotitaBlock.build(Posotita.apostrofos_yporroi, Gorgon.gorgon, 'θρος'),
	PosotitaBlock.build(Posotita.oligon, Isokratima.di_kato, 'η'),
	PosotitaBlock.build(Posotita.kentimata, 'η'),
	PosotitaBlock.build(Posotita.petasti, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ην'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, Character.vareia, 'βα'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.gorgon, 'α'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'θυς'),
	MartyriaBlock.build(Fthongos.di_kato, MartyrikoSimadi.delta),
	PosotitaBlock.build(Posotita.oligon_ypsili_aristera, Isokratima.vou, 'και'),
	Block.stavros,
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, 'αι'),
	PosotitaBlock.build(Posotita.oligon, 'Γυ'),
	PosotitaBlock.build(Posotita.petasti, Chronos.klasma, 'ναι'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.apli, Character.antikenoma, 'κε'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ες'),
	PosotitaBlock.build(Posotita.petasti_oligon, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ηλ'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'θον'),
	MartyriaBlock.build(Fthongos.vou, MartyrikoSimadi.lambda),
	PosotitaBlock.build(Posotita.oligon_kentima_dipla, Gorgon.gorgon_kato, Isokratima.pa, 'ε'),
	PosotitaBlock.build(Posotita.ison, 'πι'),
	PosotitaBlock.build(Posotita.ison, 'το'),
	PosotitaBlock.build(Posotita.petasti, 'μνη'),
	PosotitaBlock.build(Posotita.apostrofos, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'η'),
	PosotitaBlock.build(Posotita.ison, Character.vareia, 'μα'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.digorgon, 'α'),
	PosotitaBlock.build(Posotita.kentimata, 'α'),
	PosotitaBlock.build(Posotita.oligon, 'α'),
	PosotitaBlock.build(Posotita.ison, Gorgon.gorgon, Character.omalon_diplo, 'α'),
	PosotitaBlock.build(Posotita.apostrofos_kentimata, Gorgon.gorgon, 'σου'),
	PosotitaBlock.build(Posotita.apostrofos, 'ου'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'Χρι'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ι'),
	PosotitaBlock.build(Posotita.apostrofos, 'ι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, Character.rythmos_trisimos, 'στε'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	Block.newline,
);

block_list.push(
	new IchosBlock(Ichos.plagios_protos, Vathmida.ke, Fthora.diatoniki_pa), // TODO support correct notation
	Block.newline,
	PosotitaBlock.build(Posotita.petasti_ison, Isokratima.ke, 'Κυ'),
	PosotitaBlock.build(Posotita.apostrofos, 'ρι'),
	PosotitaBlock.build(Posotita.oligon, 'ε'),
	Block.stavros,
	PosotitaBlock.build(Posotita.oligon, 'ε'),
	PosotitaBlock.build(Posotita.oligon, 'κε'),
	PosotitaBlock.build(Posotita.ison, 'κρα'),
	PosotitaBlock.build(Posotita.ison, 'ξα'),
	PosotitaBlock.build(Posotita.apostrofos, 'προς'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'σε'),
	PosotitaBlock.build(Posotita.apostrofos, 'ει'),
	PosotitaBlock.build(Posotita.apostrofos, 'σα'),
	PosotitaBlock.build(Posotita.oligon, 'κου'),
	PosotitaBlock.build(Posotita.ison, 'σο'),
	PosotitaBlock.build(Posotita.kentimata, 'ον'),
	PosotitaBlock.build(Posotita.ison, 'μου'),
	PosotitaBlock.build(Posotita.ison, 'ει'),
	PosotitaBlock.build(Posotita.apostrofos, 'σα'),
	PosotitaBlock.build(Posotita.apostrofos, 'κου'),
	PosotitaBlock.build(Posotita.oligon, 'σον'),
	PosotitaBlock.build(Posotita.ison, 'μου'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'Κυ'),
	PosotitaBlock.build(Posotita.apostrofos, 'ρι'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'ε'),
	MartyriaBlock.build(Fthongos.ke, MartyrikoSimadi.alfa),
	PosotitaBlock.build(Posotita.petasti_kentima, 'Κυ'),
	PosotitaBlock.build(Posotita.apostrofos, 'ρι'),
	PosotitaBlock.build(Posotita.ison, 'ε'),
	Block.stavros,
	PosotitaBlock.build(Posotita.oligon, 'ε'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'κε'),
	PosotitaBlock.build(Posotita.apostrofos, 'κρα'),
	PosotitaBlock.build(Posotita.apostrofos, 'ξα'),
	PosotitaBlock.build(Posotita.apostrofos, 'προς'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'σε'),
	PosotitaBlock.build(Posotita.apostrofos, 'ει'),
	PosotitaBlock.build(Posotita.apostrofos, 'σα'),
	PosotitaBlock.build(Posotita.oligon, 'κου'),
	PosotitaBlock.build(Posotita.ison, 'σο'),
	PosotitaBlock.build(Posotita.kentimata, 'ον'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'μου'),
	MartyriaBlock.build(Fthongos.ni_ano, MartyrikoSimadi.nana),
	PosotitaBlock.build(Posotita.petasti, 'προ'),
	PosotitaBlock.build(Posotita.apostrofos, 'σχες'),
	PosotitaBlock.build(Posotita.ison, 'τη'),
	PosotitaBlock.build(Posotita.apostrofos, 'φω'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, 'νη'),
	PosotitaBlock.build(Posotita.elafron_apostrofos, Isokratima.di, 'της'),
	PosotitaBlock.build(Posotita.oligon, Isokratima.ke, 'δε'),
	PosotitaBlock.build(Posotita.oligon, 'η'),
	PosotitaBlock.build(Posotita.oligon, 'σε'),
	PosotitaBlock.build(Posotita.ison, Character.vareia, 'ω'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.apli, Gorgon.gorgon, 'ως'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'μου'),
	MartyriaBlock.build(Fthongos.ke, MartyrikoSimadi.alfa),
	PosotitaBlock.build(Posotita.apostrofos, 'εν'),
	PosotitaBlock.build(Posotita.ison, 'τω'),
	PosotitaBlock.build(Posotita.oligon, 'κε'),
	PosotitaBlock.build(Posotita.oligon, 'κρα'),
	PosotitaBlock.build(Posotita.oligon, 'γε'),
	PosotitaBlock.build(Posotita.ison, 'ναι'),
	PosotitaBlock.build(Posotita.apostrofos, 'με'),
	PosotitaBlock.build(Posotita.apostrofos, 'προς'),
	PosotitaBlock.build(Posotita.petasti, 'σε'),
	PosotitaBlock.build(Posotita.apostrofos, 'ει'),
	PosotitaBlock.build(Posotita.ison, Character.psifiston, 'σα'),
	PosotitaBlock.build(Posotita.apostrofos, 'κου'),
	PosotitaBlock.build(Posotita.apostrofos, 'σον'),
	PosotitaBlock.build(Posotita.oligon, 'μου'),
	PosotitaBlock.build(Posotita.oligon_kentimata, 'Κυ'),
	PosotitaBlock.build(Posotita.ison, Character.vareia, 'ρι'),
	PosotitaBlock.build(Posotita.apostrofos, 'ι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'ε'),
	MartyriaBlock.build(Fthongos.ke, MartyrikoSimadi.alfa),
	Block.newline,
);

block_list.push(
	new IchosBlock(Ichos.plagios_tetartos, Vathmida.ni, Fthora.diatoniki_ni),
	Block.newline,
	PosotitaBlock.build(Posotita.oligon_kentima_dipla, Isokratima.ni, 'Κυ'),
	PosotitaBlock.build(Posotita.kentimata_oligon, Gorgon.gorgon, 'υ'),
	PosotitaBlock.build(Posotita.ison, 'ρι'),
	PosotitaBlock.build(Posotita.ison, 'ε'),
	PosotitaBlock.build(Posotita.ison, 'ο'),
	PosotitaBlock.build(Posotita.kentimata_oligon, Gorgon.gorgon, Alloiosi.yfesi_apli, 'ο'),
	PosotitaBlock.build(Posotita.elafron, 'πλον'),
	PosotitaBlock.build(Posotita.ison, 'κα'),
	PosotitaBlock.build(Posotita.petasti_ison, Fthora.chromatiki_malaki_di, Isokratima.di, 'τα'), // TODO fthora position
	PosotitaBlock.build(Posotita.apostrofos, Alloiosi.diesi_apli, 'του'),
	PosotitaBlock.build(Posotita.oligon, 'δι'),
	PosotitaBlock.build(Posotita.oligon, 'α'),
	PosotitaBlock.build(Posotita.petasti, 'βο'),
	PosotitaBlock.build(Posotita.apostrofos, 'ο'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ο'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'λου'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.defteros_teleies),
	PosotitaBlock.build(Posotita.ison, Fthora.diatoniki_di, Isokratima.ni, 'τον'), // TODO fthora position
	PosotitaBlock.build(Posotita.ison, 'Σταυ'),
	PosotitaBlock.build(Posotita.petasti_ison, 'ρον'),
	PosotitaBlock.build(Posotita.apostrofos, 'σου'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'η'),
	PosotitaBlock.build(Posotita.kentimata, Gorgon.gorgon_kato, 'η'),
	PosotitaBlock.build(Posotita.oligon, 'μιν'),
	PosotitaBlock.build(Posotita.oligon_apostrofos, Character.psifiston, 'δε'),
	PosotitaBlock.build(Posotita.apostrofos, 'δω'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'κας'),
	MartyriaBlock.build(Fthongos.ni, MartyrikoSimadi.delta),
	PosotitaBlock.build(Posotita.petasti_kentima_ypsili_kentro, Chronos.klasma, Isokratima.di, 'φριτ'), // TODO isokratima position
	PosotitaBlock.build(Posotita.apostrofos, Alloiosi.yfesi_apli, 'τει'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.apostrofos, 'ει'),
	PosotitaBlock.build(Posotita.apostrofos, 'γαρ'),
	PosotitaBlock.build(Posotita.oligon, 'και'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Character.psifiston, 'τρε'),
	PosotitaBlock.build(Posotita.apostrofos, Alloiosi.yfesi_apli, 'ε'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.apostrofos, 'ε'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, Character.rythmos_trisimos, 'μει'),
	PosotitaBlock.build(Posotita.oligon, Isokratima.ni, 'μη'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_apostrofos, Character.psifiston, 'φε'),
	PosotitaBlock.build(Posotita.apostrofos, 'ρων'),
	PosotitaBlock.build(Posotita.apostrofos, 'κα'),
	PosotitaBlock.build(Posotita.oligon, 'θο'),
	PosotitaBlock.build(Posotita.petasti, 'ραν'),
	PosotitaBlock.build(Posotita.apostrofos, 'αυ'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'του'),
	PosotitaBlock.build(Posotita.kentimata, Gorgon.gorgon_kato, 'ου'),
	PosotitaBlock.build(Posotita.oligon, 'την'),
	PosotitaBlock.build(Posotita.oligon_apostrofos, Character.psifiston, 'δυ'),
	PosotitaBlock.build(Posotita.apostrofos, 'να'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'μιν'),
	MartyriaBlock.build(Fthongos.ni, MartyrikoSimadi.delta),
	Block.diastoli,
	PosotitaBlock.build(Posotita.petasti, Character.rythmos_trisimos, 'ο'),
	PosotitaBlock.build(Posotita.apostrofos, 'τι'),
	PosotitaBlock.build(Posotita.ison, 'νε'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Character.vareia, 'κρου'),
	PosotitaBlock.build(Posotita.apostrofos, Alloiosi.diesi_apli, 'ους'),
	PosotitaBlock.build(Posotita.oligon, 'α'),
	PosotitaBlock.build(Posotita.oligon, 'νι'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Character.rythmos_trisimos, 'στα'),
	PosotitaBlock.build(Posotita.ison, 'και'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentima_kato, Character.psifiston, Chroa.zygos, 'θα'),
	PosotitaBlock.build(Posotita.apostrofos, 'να'),
	PosotitaBlock.build(Posotita.apostrofos, 'τον'),
	PosotitaBlock.build(Posotita.apostrofos, 'κα'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'τη'),
	PosotitaBlock.build(Posotita.apostrofos, 'ργη'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'σε'),
	MartyriaBlock.build(Fthongos.ni, MartyrikoSimadi.zygos),
	PosotitaBlock.build(Posotita.oligon_kentima_dipla, Fthora.diatoniki_vou, 'δι'),
	PosotitaBlock.build(Posotita.oligon, 'α'),
	PosotitaBlock.build(Posotita.petasti, 'του'),
	PosotitaBlock.build(Posotita.elafron, 'το'),
	PosotitaBlock.build(Posotita.oligon, 'προ'),
	PosotitaBlock.build(Posotita.oligon, 'σκυ'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon, Alloiosi.yfesi_apli, 'νου'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.apostrofos, 'ου'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'μεν'),
	PosotitaBlock.build(Posotita.ison, 'την'),
	PosotitaBlock.build(Posotita.ison, 'τα'),
	PosotitaBlock.build(Posotita.ison, Character.psifiston, Isokratima.pa, 'φην'),
	PosotitaBlock.build(Posotita.apostrofos, 'σου'),
	PosotitaBlock.build(Posotita.apostrofos, 'και'),
	PosotitaBlock.build(Posotita.apostrofos, 'την'),
	PosotitaBlock.build(Posotita.oligon_kentima_kato, Character.psifiston, Isokratima.ni, 'ε'),
	PosotitaBlock.build(Posotita.apostrofos, 'ε'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.apli, Character.antikenoma, 'γε'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ερ'),
	Block.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'σιν'),
	MartyriaBlock.build(Fthongos.ni, MartyrikoSimadi.delta),
);
