import { AbstractBlock } from './block-abstract.js';
import { SimpleBlock } from './block-simple.js';
import { IchosBlock } from './block-ichos.js';
import { PosotitaBlock } from './block-posotita.js';
import { MartyriaBlock } from './block-martyria.js';
import { AgogiBlock } from './block-agogi.js';
import { Ichos } from './ichos.js';
import { Posotita } from './posotita.js';
import { Character } from './character.js';
import { Chronos } from './chronos.js';
import { Gorgon } from './gorgon.js';
import { Alloiosi } from './alloiosi.js';
import { Fthora } from './fthora.js';
import { Chroa } from './chroa.js';
import { Isokratima } from './isokratima.js';
import { Vathmida } from './vathmida.js';
import { Fthongos } from './fthongos.js';
import { MartyrikoSimadi } from './martyriko-simadi.js';
import { Agogi } from './agogi.js';

/**
 * @type {AbstractBlock[]}
 */
export const block_list = [];

// block_list.push(
// 	new IchosBlock(Ichos.plagios_tetartos, Vathmida.ni, Fthora.diatoniki_ni),
// 	AbstractBlock.newline,
// 	// Εκ νεότητός μου
// 	new PosotitaBlock(Posotita.ison, Isokratima.ni, 'Εκ'),
// 	new PosotitaBlock(Posotita.ison, 'νε'),
// 	new PosotitaBlock(Posotita.oligon_kentima_dipla, 'ο'),
// 	new PosotitaBlock(Posotita.oligon, 'τη'),
// 	new PosotitaBlock(Posotita.oligon, 'τος'),
// 	new PosotitaBlock(Posotita.ison, 'μου'),
// 	new PosotitaBlock(Posotita.ison, 'ο'),
// 	new PosotitaBlock(Posotita.ison, 'εχ'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.apostrofos, 'θρο'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ος'),
// 	new PosotitaBlock(Posotita.oligon, 'με'),
// 	new PosotitaBlock(Posotita.oligon, 'πει'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, Alloiosi.yfesi_apli, 'ρα'), // NOTE my yfesi
// 	new PosotitaBlock(Posotita.elafron, 'ζει'),
// 	new PosotitaBlock(Posotita.ison, 'ταις'),
// 	new PosotitaBlock(Posotita.ison, 'η'),
// 	new PosotitaBlock(Posotita.apostrofos, 'δο'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, Character.psifiston, Alloiosi.yfesi_apli, 'ναις'),
// 	new PosotitaBlock(Posotita.apostrofos, 'φλε'),
// 	new PosotitaBlock(Posotita.apostrofos, 'γει'),
// 	new PosotitaBlock(Posotita.apostrofos, 'με'),
// 	new PosotitaBlock(Posotita.ison, 'ε'),
// 	new PosotitaBlock(Posotita.petasti_ison, 'γω'),
// 	new PosotitaBlock(Posotita.apostrofos, 'δε'),
// 	new PosotitaBlock(Posotita.oligon, 'πε'),
// 	new PosotitaBlock(Posotita.oligon, 'ποι'),
// 	new PosotitaBlock(Posotita.oligon, Chronos.klasma, 'θως'),
// 	new PosotitaBlock(Posotita.ison, 'εν'),
// 	new PosotitaBlock(Posotita.oligon, 'σοι'),
// 	new PosotitaBlock(Posotita.petasti_apostrofos, 'Κυ'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ρι'),
// 	new PosotitaBlock(Posotita.syneches_elafron, 'ε'),
// 	new PosotitaBlock(Posotita.oligon, 'τρο'),
// 	new PosotitaBlock(Posotita.oligon, Character.psifiston, 'που'),
// 	new PosotitaBlock(Posotita.apostrofos, 'μαι'),
// 	new PosotitaBlock(Posotita.apostrofos_kentimata, 'του'),
// 	new PosotitaBlock(Posotita.elafron, Chronos.klasma, 'τον'),
// 	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.delta),
// 	AbstractBlock.newline,
// 	// Οι μισούντες Σιών
// 	new PosotitaBlock(Posotita.oligon_kentima_dipla, Isokratima.ni, 'Οι'),
// 	new PosotitaBlock(Posotita.oligon, 'μι'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.petasti, Character.rythmos_trisimos, 'σου'),
// 	new PosotitaBlock(Posotita.elafron, 'ντες'),
// 	new PosotitaBlock(Posotita.oligon, 'Σι'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon, Chronos.klasma, 'ων'),
// 	new PosotitaBlock(Posotita.ison, 'γε'),
// 	new PosotitaBlock(Posotita.ison, 'νη'),
// 	new PosotitaBlock(Posotita.ison, 'θη'),
// 	new PosotitaBlock(Posotita.kentimata, 'η'),
// 	new PosotitaBlock(Posotita.ison, 'τω'),
// 	new PosotitaBlock(Posotita.elafron, 'σαν'),
// 	new PosotitaBlock(Posotita.oligon, Chronos.klasma, 'δη'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.ison, Character.rythmos_trisimos, 'πριν'),
// 	new PosotitaBlock(Posotita.ison, 'εκ'),
// 	new PosotitaBlock(Posotita.ison, 'σπα'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.elafron_apostrofos, 'σθη'),
// 	new PosotitaBlock(Posotita.kentimata, 'η'),
// 	new PosotitaBlock(Posotita.ison, 'ναι'),
// 	new PosotitaBlock(Posotita.elafron, 'ως'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, 'χορ'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.elafron, Chronos.klasma, Character.rythmos_trisimos, 'τος'),
// 	new PosotitaBlock(Posotita.oligon, 'συγ'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.petasti, 'κο'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ψει'),
// 	new PosotitaBlock(Posotita.oligon, 'γαρ'),
// 	new PosotitaBlock(Posotita.oligon, 'Χρι'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon, Chronos.klasma, Character.rythmos_trisimos, 'στος'),
// 	SimpleBlock.stavros,
// 	new PosotitaBlock(Posotita.ison, 'αυ'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon_kentimata, Gorgon.gorgon, Alloiosi.yfesi_apli, 'χε'), // NOTE my yfesi
// 	new PosotitaBlock(Posotita.apostrofos, 'ε'),
// 	new PosotitaBlock(Posotita.apostrofos, 'νας'),
// 	new PosotitaBlock(Posotita.ison, 'αυ'),
// 	new PosotitaBlock(Posotita.elafron_apostrofos, 'των'),
// 	new PosotitaBlock(Posotita.oligon, 'το'),
// 	new PosotitaBlock(Posotita.ison, 'μη'),
// 	new PosotitaBlock(Posotita.elafron, 'βα'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, 'σα'),
// 	new PosotitaBlock(Posotita.elafron, Chronos.klasma, 'νων'),
// 	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.delta),
// 	AbstractBlock.newline,
// 	// Δόξα, Και νυν
// 	SimpleBlock.diastoli,
// 	new AgogiBlock(Agogi.tacheia),
// 	new PosotitaBlock(Posotita.oligon_ypsili_dexia, Isokratima.ni, Character.rythmos_trisimos, 'Δο'),
// 	new PosotitaBlock(Posotita.ison, 'ξα'),
// 	new PosotitaBlock(Posotita.ison, 'Πα'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon_ison, Character.rythmos_trisimos, 'τρι'),
// 	new PosotitaBlock(Posotita.ison, 'και'),
// 	new PosotitaBlock(Posotita.ison, 'Υι'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon_ison, Character.rythmos_trisimos, 'ω'),
// 	new PosotitaBlock(Posotita.ison, 'και'),
// 	new PosotitaBlock(Posotita.ison, 'Α'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.apostrofos, 'γι'),
// 	new PosotitaBlock(Posotita.oligon, 'ω'),
// 	new PosotitaBlock(Posotita.petasti, 'Πνευ'),
// 	new PosotitaBlock(Posotita.apostrofos, 'μα'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, Character.rythmos_trisimos, 'τι'),
// 	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.delta_teleies),
// 	new PosotitaBlock(Posotita.chamili, 'και'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon_ypsili_dexia, Character.rythmos_trisimos, 'νυν'),
// 	new PosotitaBlock(Posotita.ison, 'και'),
// 	new PosotitaBlock(Posotita.ison, 'α'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.petasti, Character.rythmos_trisimos, 'ει'),
// 	new PosotitaBlock(Posotita.apostrofos, 'και'),
// 	new PosotitaBlock(Posotita.ison, 'εις'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.ison, 'τους'),
// 	new PosotitaBlock(Posotita.ison, 'αι'),
// 	new AgogiBlock(Agogi.metria),
// 	new PosotitaBlock(Posotita.ison, Character.psifiston, 'ω'),
// 	new PosotitaBlock(Posotita.apostrofos, 'νας'),
// 	new PosotitaBlock(Posotita.apostrofos, 'των'),
// 	new PosotitaBlock(Posotita.apostrofos, 'αι'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, Character.psifiston, 'ω'),
// 	new PosotitaBlock(Posotita.apostrofos, 'νων'),
// 	new PosotitaBlock(Posotita.apostrofos, 'α'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, Character.rythmos_trisimos, 'μην'), // TODO rythmos on klasma
// 	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.delta),
// 	AbstractBlock.newline,
// 	// Αγίω Πνεύματι
// 	new PosotitaBlock(Posotita.ison, Isokratima.ni, 'Α'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon_kentima_dipla, 'γι'),
// 	new PosotitaBlock(Posotita.oligon, 'ω'),
// 	new PosotitaBlock(Posotita.oligon, 'Πνευ'),
// 	new PosotitaBlock(Posotita.ison, 'μα'),
// 	new PosotitaBlock(Posotita.ison, 'τι'),
// 	new PosotitaBlock(Posotita.ison, 'το'),
// 	new PosotitaBlock(Posotita.petasti, 'ζην'),
// 	new PosotitaBlock(Posotita.apostrofos, 'τα'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon_kentimata, Alloiosi.yfesi_apli, Character.rythmos_trisimos, 'παν'), // NOTE my yfesi
// 	new PosotitaBlock(Posotita.elafron, 'τα'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.petasti, Character.rythmos_trisimos, 'φως'),
// 	new PosotitaBlock(Posotita.apostrofos, 'εκ'),
// 	new PosotitaBlock(Posotita.ison, 'φω'),
// 	SimpleBlock.diastoli,
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.apostrofos, 'το'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ος'),
// 	new PosotitaBlock(Posotita.oligon, 'Θε'),
// 	new PosotitaBlock(Posotita.oligon, 'ος'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, Alloiosi.yfesi_apli, 'με'), // NOTE my yfesi
// 	new PosotitaBlock(Posotita.elafron, Chronos.klasma, 'γας'),
// 	new PosotitaBlock(Posotita.ison, 'συν'),
// 	new PosotitaBlock(Posotita.oligon, 'Πα'),
// 	new PosotitaBlock(Posotita.petasti, Alloiosi.yfesi_apli, 'τρι'), // NOTE my yfesi
// 	SimpleBlock.stavros,
// 	new PosotitaBlock(Posotita.elafron, 'υ'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.oligon, 'μνου'),
// 	new PosotitaBlock(Posotita.ison, Character.omalon_diplo, 'ου'),
// 	new PosotitaBlock(Posotita.apostrofos, 'μεν'),
// 	new PosotitaBlock(Posotita.ison, 'αυ'),
// 	new PosotitaBlock(Posotita.elafron_apostrofos, 'το'),
// 	new PosotitaBlock(Posotita.kentimata, 'ο'),
// 	new PosotitaBlock(Posotita.ison, 'και'),
// 	new PosotitaBlock(Posotita.elafron, 'τω'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, 'Λο'),
// 	new PosotitaBlock(Posotita.elafron, Chronos.klasma, 'γω'),
// 	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.delta),
// 	AbstractBlock.newline,
// );

block_list.push(
	new IchosBlock(Ichos.protos, Vathmida.pa, Fthora.diatoniki_pa),
	AbstractBlock.newline,
	PosotitaBlock.build(Posotita.petasti, Isokratima.pa, 'Κυ'),
	PosotitaBlock.build(Posotita.apostrofos, 'ρι'),
	PosotitaBlock.build(Posotita.ison, 'ε'),
	SimpleBlock.stavros,
	PosotitaBlock.build(Posotita.oligon, 'ε'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Character.psifiston, 'κε'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'κρα'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.apli, Character.antikenoma, 'ξα'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, Isokratima.melos, 'α'),
	PosotitaBlock.build(Posotita.ison, Character.vareia, 'προ'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ο'),
	PosotitaBlock.build(Posotita.oligon, 'ος'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.petasti_oligon, Character.rythmos_tetrasimos, 'σε'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'ε'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	PosotitaBlock.build(Posotita.ison, Isokratima.pa, 'ει'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.petasti_kentima, Chronos.klasma, 'σα'),
	PosotitaBlock.build(Posotita.apostrofos_kentimata, 'κου'),
	PosotitaBlock.build(Posotita.apostrofos_yporroi, Chronos.klasma, Gorgon.gorgon, 'σο'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ο'),
	PosotitaBlock.build(Posotita.apostrofos, 'ον'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'μου'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon_kato, 'ει'),
	PosotitaBlock.build(Posotita.oligon, 'σα'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, Alloiosi.yfesi_apli, 'α'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'κου'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.apli, Gorgon.gorgon, 'ου'),
	PosotitaBlock.build(Posotita.ison_kentimata, Gorgon.gorgon, 'σο'),
	PosotitaBlock.build(Posotita.apostrofos, 'ον'),
	PosotitaBlock.build(Posotita.apostrofos, Character.vareia, Isokratima.melos, 'μου'),
	PosotitaBlock.build(Posotita.apostrofos, 'ου'),
	PosotitaBlock.build(Posotita.oligon, 'Κυ'),
	PosotitaBlock.build(Posotita.kentimata_oligon, Isokratima.pa, 'υ'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon, 'υ'),
	PosotitaBlock.build(Posotita.apostrofos_yporroi, Chronos.klasma, Gorgon.gorgon, Character.vareia, 'ρι'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ι'),
	PosotitaBlock.build(Posotita.apostrofos, 'ι'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'ε'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	PosotitaBlock.build(Posotita.petasti_kentima, 'Κυ'),
	PosotitaBlock.build(Posotita.apostrofos, 'ρι'),
	PosotitaBlock.build(Posotita.ison, 'ε'),
	SimpleBlock.stavros,
	PosotitaBlock.build(Posotita.oligon, 'ε'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Character.psifiston, Alloiosi.yfesi_apli, 'κε'),
	PosotitaBlock.build(Posotita.apostrofos, 'κρα'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.petasti_apostrofos, Chronos.klasma, 'ξα'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'προ'),
	PosotitaBlock.build(Posotita.kentimata, 'ος'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon, 'σε'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'ε'),
	MartyriaBlock.build(Fthongos.ga, MartyrikoSimadi.nana),
	PosotitaBlock.build(Posotita.elafron, 'ει'),
	PosotitaBlock.build(Posotita.ison, 'σα'),
	PosotitaBlock.build(Posotita.ison, 'κου'),
	PosotitaBlock.build(Posotita.oligon_kentima_kato, Chronos.klasma, Isokratima.zo, Character.psifiston, 'σο'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.gorgon, 'ο'),
	PosotitaBlock.build(Posotita.apostrofos, 'ο'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ον'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon, Character.vareia, Character.rythmos_trisimos, 'μου'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.digorgon, 'ου'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, 'ου'),
	MartyriaBlock.build(Fthongos.zo, MartyrikoSimadi.varys),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon_ypsili_aristera, Chronos.klasma, Isokratima.pa, Character.omalon_mono, 'προ'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'σχες'),
	PosotitaBlock.build(Posotita.ison, 'τη'),
	PosotitaBlock.build(Posotita.apostrofos, 'φω'),
	PosotitaBlock.build(Posotita.oligon, 'νη'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'η'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.gorgon, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, Character.vareia, Isokratima.melos, 'τη'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'η'),
	PosotitaBlock.build(Posotita.oligon, 'ης'),
	SimpleBlock.stavros,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Isokratima.pa, 'δε'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, 'η'),
	PosotitaBlock.build(Posotita.oligon_kentimata, 'σε'),
	PosotitaBlock.build(Posotita.apostrofos_yporroi, Chronos.klasma, Gorgon.gorgon, Character.vareia, 'ω'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ω'),
	PosotitaBlock.build(Posotita.apostrofos, 'ως'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'μου'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	PosotitaBlock.build(Posotita.oligon_kentima_dipla, 'εν'),
	PosotitaBlock.build(Posotita.ison, 'τω'),
	PosotitaBlock.build(Posotita.apostrofos, 'κε'),
	PosotitaBlock.build(Posotita.oligon, 'κρα'),
	PosotitaBlock.build(Posotita.oligon_ypsili_dexia, Chronos.klasma, Isokratima.di, Character.psifiston, 'γε'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'ναι'), // TODO enarmonia fthora
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, Isokratima.pa, 'με'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.apli, Character.antikenoma, 'προ'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ος'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentima_kato, Character.vareia, Character.rythmos_tetrasimos, 'σε'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.trigorgon, 'ε'),
	PosotitaBlock.build(Posotita.apostrofos, 'ε'),
	PosotitaBlock.build(Posotita.oligon_kentimata, Gorgon.gorgon, 'ε'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'ε'),
	MartyriaBlock.build(Fthongos.ga, MartyrikoSimadi.nana, Fthora.diatoniki_ga),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon_kato, 'ει'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentimata, 'σα'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, 'κου'),
	PosotitaBlock.build(Posotita.apostrofos_kentimata, Gorgon.gorgon, 'σο'),
	PosotitaBlock.build(Posotita.apostrofos, 'ον'),
	PosotitaBlock.build(Posotita.syneches_elafron, Chronos.klasma, 'μου'),
	PosotitaBlock.build(Posotita.oligon, 'Κυ'),
	PosotitaBlock.build(Posotita.kentimata, 'υ'),
	PosotitaBlock.build(Posotita.petasti, Chronos.klasma, Character.psifiston, 'υ'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'υ'),
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, Character.vareia, 'ρι'),
	PosotitaBlock.build(Posotita.yporroi, Gorgon.gorgon, 'ι'),
	PosotitaBlock.build(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ι'),
	PosotitaBlock.build(Posotita.apostrofos, 'ι'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'ε'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	AbstractBlock.newline,
);

block_list.push(
	new IchosBlock(Ichos.protos, Vathmida.pa, Fthora.diatoniki_pa),
	AbstractBlock.newline,
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentima, Isokratima.pa, Character.rythmos_trisimos, 'Δευ'), // TODO isokratima position
	PosotitaBlock.build(Posotita.ison, 'τε'),
	PosotitaBlock.build(Posotita.apostrofos, 'λα'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon, 'οι'),
	PosotitaBlock.build(Posotita.oligon, 'υ'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, Alloiosi.yfesi_apli, 'μνη'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.apostrofos, 'σω'),
	PosotitaBlock.build(Posotita.apostrofos, 'μεν'),
	PosotitaBlock.build(Posotita.ison, 'και'),
	PosotitaBlock.build(Posotita.ison, 'προ'),
	PosotitaBlock.build(Posotita.ison, 'σκυ'),
	PosotitaBlock.build(Posotita.apostrofos, 'νη'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'σω'),
	PosotitaBlock.build(Posotita.oligon, 'μεν'),
	PosotitaBlock.build(Posotita.oligon, 'Χρι'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Character.rythmos_trisimos, 'στον'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies),
	PosotitaBlock.build(Posotita.ison, 'δο'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon, 'ξα'),
	PosotitaBlock.build(Posotita.ison, 'ζο'),
	PosotitaBlock.build(Posotita.apostrofos, 'ντες'),
	PosotitaBlock.build(Posotita.apostrofos, 'αυ'),
	PosotitaBlock.build(Posotita.oligon, 'του'),
	PosotitaBlock.build(Posotita.ison, 'την'),
	PosotitaBlock.build(Posotita.apostrofos, 'εκ'),
	PosotitaBlock.build(Posotita.apostrofos, 'νε'),
	PosotitaBlock.build(Posotita.oligon, 'κρων'),
	PosotitaBlock.build(Posotita.oligon, 'α'),
	PosotitaBlock.build(Posotita.ison, Character.psifiston, 'να'),
	PosotitaBlock.build(Posotita.apostrofos, 'στα'),
	PosotitaBlock.build(Posotita.syneches_elafron, Chronos.klasma, 'σιν'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.petasti_ypsili_dexia, Character.rythmos_trisimos, 'ο'),
	PosotitaBlock.build(Posotita.elafron, 'τι'),
	PosotitaBlock.build(Posotita.oligon, 'αυ'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon, 'τος'),
	PosotitaBlock.build(Posotita.ison, 'ε'),
	PosotitaBlock.build(Posotita.ison, Character.vareia, 'στι'),
	PosotitaBlock.build(Posotita.apostrofos, 'ιν'),
	PosotitaBlock.build(Posotita.oligon, 'ο'),
	PosotitaBlock.build(Posotita.ison, 'Θε'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, Alloiosi.yfesi_apli, 'ος'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.apostrofos, 'η'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, Character.rythmos_trisimos, 'μων'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies),
	PosotitaBlock.build(Posotita.elafron_apostrofos, Fthora.chromatiki_skliri_pa, 'ο'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon, 'εκ'),
	PosotitaBlock.build(Posotita.oligon, 'της'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'πλα'),
	PosotitaBlock.build(Posotita.apostrofos, 'νης'),
	PosotitaBlock.build(Posotita.apostrofos, 'του'),
	PosotitaBlock.build(Posotita.oligon, 'εχ'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Character.rythmos_trisimos, 'θρου'),
	PosotitaBlock.build(Posotita.ison, Fthora.diatoniki_di, 'τον'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.petasti_ison, 'κο'),
	PosotitaBlock.build(Posotita.apostrofos, 'σμον'),
	PosotitaBlock.build(Posotita.ison, 'λυ'),
	PosotitaBlock.build(Posotita.apostrofos, 'τρω'),
	PosotitaBlock.build(Posotita.oligon_kentima_kato, Character.psifiston, 'σα'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.apli, Character.antikenoma, 'με'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ε'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'νος'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	AbstractBlock.newline,
	new AgogiBlock(Agogi.tacheia),
	PosotitaBlock.build(Posotita.ison, Isokratima.pa, 'Γε'),
	PosotitaBlock.build(Posotita.ison, Gorgon.gorgon_kato, 'νη'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentima, Character.rythmos_trisimos, 'θη'),
	PosotitaBlock.build(Posotita.ison, 'τω'),
	PosotitaBlock.build(Posotita.ison, 'τα'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon_ison, 'ω'),
	PosotitaBlock.build(Posotita.ison, 'τα'),
	PosotitaBlock.build(Posotita.ison, 'σου'),
	PosotitaBlock.build(Posotita.ison, 'προ'),
	PosotitaBlock.build(Posotita.petasti, 'σε'),
	PosotitaBlock.build(Posotita.apostrofos, 'χο'),
	PosotitaBlock.build(Posotita.ison, 'ντα'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies),
	PosotitaBlock.build(Posotita.apostrofos, 'εις'),
	PosotitaBlock.build(Posotita.apostrofos, 'την'),
	PosotitaBlock.build(Posotita.oligon, 'φω'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, 'νην'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies, Agogi.metria),
	PosotitaBlock.build(Posotita.petasti_ison, 'της'),
	PosotitaBlock.build(Posotita.apostrofos, 'δε'),
	PosotitaBlock.build(Posotita.petasti_ison, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, 'σε'),
	PosotitaBlock.build(Posotita.oligon_kentimata, 'ως'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.klasma, Chronos.rythmos_trisimos, 'μου'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies),
	AbstractBlock.newline,
	PosotitaBlock.build(Posotita.ison, Isokratima.pa, 'Ευ'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.petasti, Chronos.klasma, 'φρα'),
	PosotitaBlock.build(Posotita.apostrofos, 'νθη'),
	PosotitaBlock.build(Posotita.apostrofos, 'τε'),
	PosotitaBlock.build(Posotita.apostrofos, 'ου'),
	PosotitaBlock.build(Posotita.oligon, 'ρα'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Isokratima.di, Character.rythmos_trisimos, 'νοι'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies),
	PosotitaBlock.build(Posotita.ison, 'σαλ'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon_kentima, Character.psifiston, 'πι'),
	PosotitaBlock.build(Posotita.apostrofos, Alloiosi.yfesi_apli, 'ι'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.apostrofos, 'σα'),
	PosotitaBlock.build(Posotita.apostrofos, 'τε'),
	PosotitaBlock.build(Posotita.ison, Isokratima.pa, 'τα'),
	PosotitaBlock.build(Posotita.apostrofos, 'θε'),
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'με'),
	PosotitaBlock.build(Posotita.apostrofos, 'λι'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.oligon, 'της'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Isokratima.di, Character.rythmos_trisimos, 'γης'),
	MartyriaBlock.build(Fthongos.di, MartyrikoSimadi.delta_teleies),
	PosotitaBlock.build(Posotita.ison, 'βο'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.petasti_kentima, Chronos.klasma, 'η'),
	PosotitaBlock.build(Posotita.apostrofos, Alloiosi.yfesi_apli, 'σα'), // NOTE my yfesi
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, Isokratima.pa, 'τε'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'τα'),
	PosotitaBlock.build(Posotita.oligon_kentima_dipla, 'ο'),
	PosotitaBlock.build(Posotita.ison, 'ρη'),
	PosotitaBlock.build(Posotita.ison, 'ευ'),
	PosotitaBlock.build(Posotita.apostrofos, 'φρο'),
	PosotitaBlock.build(Posotita.ison, Character.psifiston, 'συ'),
	PosotitaBlock.build(Posotita.apostrofos, 'υ'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'νην'),
	PosotitaBlock.build(Posotita.oligon_kentima, 'ι'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, 'δου'),
	PosotitaBlock.build(Posotita.apostrofos, 'γαρ'),
	PosotitaBlock.build(Posotita.apostrofos, 'ο'),
	PosotitaBlock.build(Posotita.syneches_elafron, 'Εμ'),
	PosotitaBlock.build(Posotita.oligon, 'μα'),
	PosotitaBlock.build(Posotita.oligon, 'νου'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Character.rythmos_trisimos, 'ηλ'),
	PosotitaBlock.build(Posotita.elafron_apostrofos, Isokratima.melos, 'τας'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.ison, 'α'),
	PosotitaBlock.build(Posotita.ison, 'μαρ'),
	PosotitaBlock.build(Posotita.petasti_ison, Chronos.klasma, Fthora.chromatiki_skliri_di, 'τι'), // TODO fthora position, fthongos hint
	PosotitaBlock.build(Posotita.syneches_elafron, 'ας'),
	PosotitaBlock.build(Posotita.oligon, 'η'),
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, Isokratima.pa, 'μων'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.skliro),
	PosotitaBlock.build(Posotita.oligon_kentima, Fthora.diatoniki_di, 'τω'), // TODO fthora position, pitch change
	PosotitaBlock.build(Posotita.ison, 'σταυ'),
	PosotitaBlock.build(Posotita.petasti_ison, 'ρω'),
	PosotitaBlock.build(Posotita.apostrofos, 'προ'),
	PosotitaBlock.build(Posotita.ison, Character.psifiston, 'ση'),
	PosotitaBlock.build(Posotita.apostrofos, 'λω'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.klasma, 'σε'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	PosotitaBlock.build(Posotita.oligon, 'και'),
	PosotitaBlock.build(Posotita.oligon, 'ζω'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.petasti, Character.rythmos_trisimos, 'ην'),
	PosotitaBlock.build(Posotita.elafron, 'ο'),
	PosotitaBlock.build(Posotita.oligon, 'δι'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon, Chronos.klasma, 'δους'),
	PosotitaBlock.build(Posotita.petasti_ison, 'θα'),
	PosotitaBlock.build(Posotita.apostrofos, 'να'),
	PosotitaBlock.build(Posotita.syneches_elafron, Chronos.klasma, Isokratima.melos, 'τον'),
	PosotitaBlock.build(Posotita.ison, Gorgon.gorgon_kato, 'ε'),
	PosotitaBlock.build(Posotita.ison_kentimata, Gorgon.gorgon, 'νε'),
	PosotitaBlock.build(Posotita.apostrofos, 'κρω'),
	PosotitaBlock.build(Posotita.syneches_elafron, Chronos.klasma, 'σε'),
	MartyriaBlock.build(Fthongos.zo, MartyrikoSimadi.varys),
	PosotitaBlock.build(Posotita.oligon_ypsili_dexia, Isokratima.pa, 'τον'),
	PosotitaBlock.build(Posotita.oligon, 'Α'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.oligon, Character.psifiston, Character.rythmos_trisimos, 'δαμ'),
	PosotitaBlock.build(Posotita.apostrofos, 'α'),
	PosotitaBlock.build(Posotita.apostrofos, 'να'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.petasti, 'στη'),
	PosotitaBlock.build(Posotita.apostrofos, 'σας'),
	PosotitaBlock.build(Posotita.ison, 'ως'),
	PosotitaBlock.build(Posotita.apostrofos, 'φι'),
	PosotitaBlock.build(Posotita.oligon_kentima_kato, Character.psifiston, 'λα'),
	PosotitaBlock.build(Posotita.apostrofos, 'αν'),
	PosotitaBlock.build(Posotita.apostrofos, Chronos.apli, Character.antikenoma, 'θρω'),
	PosotitaBlock.build(Posotita.apostrofos, Gorgon.gorgon, 'ω'),
	SimpleBlock.diastoli,
	PosotitaBlock.build(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'πος'),
	MartyriaBlock.build(Fthongos.pa, MartyrikoSimadi.alfa),
	AbstractBlock.newline,
);

// block_list.push(
// 	new IchosBlock(Ichos.defteros, Vathmida.di, Fthora.chromatiki_malaki_di),
// 	AbstractBlock.newline,
// 	new PosotitaBlock(Posotita.elafron, Isokratima.melos, 'Κυ'),
// 	new PosotitaBlock(Posotita.kentimata_oligon, Isokratima.di, 'υ'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, Gorgon.gorgon, 'υ'),
// 	new PosotitaBlock(Posotita.elafron, Chronos.klasma, 'ρι'),
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, 'ε'),
// 	SimpleBlock.stavros,
// 	new PosotitaBlock(Posotita.oligon, Chronos.klasma, 'ε'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, Character.psifiston, 'κε'),
// 	new PosotitaBlock(Posotita.apostrofos, 'κρα'),
// 	new PosotitaBlock(Posotita.apostrofos, 'α'),
// 	new PosotitaBlock(Posotita.petasti_apostrofos, Chronos.klasma, 'ξα'),
// 	new PosotitaBlock(Posotita.syneches_elafron, 'προ'),
// 	new PosotitaBlock(Posotita.kentimata, 'ος'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon, Chronos.dipli, 'σε'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ει'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon_kentimata, Character.psifiston, 'σα'),
// 	new PosotitaBlock(Posotita.apostrofos, 'α'),
// 	new PosotitaBlock(Posotita.apostrofos, 'α'),
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'κου'),
// 	new PosotitaBlock(Posotita.oligon_kentima, Chronos.apli, Character.antikenoma, 'σο'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ο'),
// 	new PosotitaBlock(Posotita.ison_kentimata, Gorgon.gorgon_meta, 'ο'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.ison, 'ο'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ον'),
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, 'μου'),
// 	new PosotitaBlock(Posotita.ison, 'ει'),
// 	new PosotitaBlock(Posotita.kentimata, 'ει'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, 'σα'),
// 	new PosotitaBlock(Posotita.apostrofos, 'κου'),
// 	new PosotitaBlock(Posotita.oligon, Character.psifiston, 'ου'),
// 	new PosotitaBlock(Posotita.yporroi, Gorgon.gorgon, 'ου'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ου'),
// 	new PosotitaBlock(Posotita.petasti, 'σον'),
// 	new PosotitaBlock(Posotita.elafron, 'μου'),
// 	new PosotitaBlock(Posotita.ison, 'Κυ'),
// 	new PosotitaBlock(Posotita.kentimata, 'υ'),
// 	new PosotitaBlock(Posotita.ison_kentimata, 'υ'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'ρι'),
// 	new PosotitaBlock(Posotita.yporroi, Gorgon.gorgon), // NOTE apostrofos yporroi
// 	new PosotitaBlock(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ι'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ι'),
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, 'ε'),
// 	new MartyriaBlock(Fthongos.vou, MartyrikoSimadi.defteros_teleies),
// 	new PosotitaBlock(Posotita.oligon_ypsili_aristera, Character.psifiston, 'Κυ'),
// 	new PosotitaBlock(Posotita.apostrofos, 'υ'),
// 	new PosotitaBlock(Posotita.elafron_kentimata, Gorgon.gorgon_meta, 'ρι'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.ison, 'ι'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ι'),
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, 'ε'),
// 	new PosotitaBlock(Posotita.ison, Gorgon.gorgon_kato, 'ε'),
// 	new PosotitaBlock(Posotita.oligon_kentima, 'κε'),
// 	new PosotitaBlock(Posotita.oligon, 'ε'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.apostrofos, 'κρα'),
// 	new PosotitaBlock(Posotita.apostrofos, 'α'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.apostrofos, 'ξα'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'α'),
// 	new PosotitaBlock(Posotita.oligon, 'α'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, Gorgon.gorgon, 'προ'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ος'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon, Chronos.dipli, Character.rythmos_tetrasimos, 'σε'),
// 	new PosotitaBlock(Posotita.elafron_apostrofos, 'ει'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, 'σα'),
// 	new PosotitaBlock(Posotita.oligon, Gorgon.gorgon_kato, 'α'),
// 	new PosotitaBlock(Posotita.ison, Character.psifiston, 'α'),
// 	new PosotitaBlock(Posotita.apostrofos, 'α'),
// 	new PosotitaBlock(Posotita.apostrofos, 'κου'),
// 	new PosotitaBlock(Posotita.kentimata, 'ου'),
// 	new PosotitaBlock(Posotita.ison_kentimata, Gorgon.gorgon_meta, 'σο'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.ison, 'ο'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ον'),
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, 'μου'),
// 	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.defteros_teleies),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.petasti_oligon, 'προ'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ο'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ο'),
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, Fthora.chromatiki_skliri_pa, 'σχες'), // TODO fthora kato
// 	new PosotitaBlock(Posotita.oligon, Chronos.klasma, 'τη'),
// 	new PosotitaBlock(Posotita.oligon_kentima_kato, Chronos.klasma, 'φω'),
// 	new PosotitaBlock(Posotita.oligon, Character.psifiston, 'νη'),
// 	new PosotitaBlock(Posotita.apostrofos, 'η'),
// 	new PosotitaBlock(Posotita.apostrofos, 'η'),
// 	new PosotitaBlock(Posotita.apostrofos, 'η'),
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'τη'),
// 	new PosotitaBlock(Posotita.kentimata_oligon, Gorgon.gorgon, 'ης'),
// 	new PosotitaBlock(Posotita.apostrofos, 'δε'),
// 	new PosotitaBlock(Posotita.petasti_oligon, Chronos.klasma, 'η'),
// 	new PosotitaBlock(Posotita.apostrofos_kentimata, 'σε'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'ω'),
// 	new PosotitaBlock(Posotita.yporroi, Gorgon.gorgon), // NOTE apostrofos yporroi
// 	new PosotitaBlock(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ω'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ως'),
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, 'μου'),
// 	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.defteros_teleies),
// 	new PosotitaBlock(Posotita.ison, 'εν'),
// 	new PosotitaBlock(Posotita.ison, 'τω'),
// 	new PosotitaBlock(Posotita.oligon, 'κε'),
// 	new PosotitaBlock(Posotita.oligon, 'κρα'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, 'γε'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.apostrofos, 'ναι'),
// 	new PosotitaBlock(Posotita.apostrofos, 'αι'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.apostrofos, 'με'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ε'),
// 	new PosotitaBlock(Posotita.oligon, 'ε'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, Gorgon.gorgon, 'προ'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ος'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon, Chronos.dipli, Character.rythmos_tetrasimos, 'σε'),
// 	SimpleBlock.stavros,
// 	new PosotitaBlock(Posotita.ison, 'ει'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon, 'σα'),
// 	new PosotitaBlock(Posotita.ison, 'κου'),
// 	new PosotitaBlock(Posotita.oligon_apostrofos, Chronos.klasma, Character.psifiston, 'σο'),
// 	new PosotitaBlock(Posotita.yporroi, Gorgon.gorgon, 'ον'),
// 	new PosotitaBlock(Posotita.apostrofos, Fthora.chromatiki_malaki_di, 'μου'), // TODO fthora kato
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.ison, 'Κυ'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, Alloiosi.diesi_apli, 'υ'),
// 	new PosotitaBlock(Posotita.ison, Character.syndesmos, 'υ'),
// 	new PosotitaBlock(Posotita.oligon, Gorgon.gorgon_kato, 'υ'),
// 	new PosotitaBlock(Posotita.ison, 'υ'),
// 	new PosotitaBlock(Posotita.kentimata, 'υ'),
// 	new PosotitaBlock(Posotita.ison_kentimata, Gorgon.gorgon, 'υ'),
// 	new PosotitaBlock(Posotita.apostrofos, 'υ'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'υ'),
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, 'ρι'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'ε'),
// 	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.defteros_teleies),
// 	AbstractBlock.newline,
// );

// block_list.push(
// 	new IchosBlock(Ichos.plagios_protos, Vathmida.pa, Fthora.diatoniki_pa),
// 	AbstractBlock.newline,
// 	new PosotitaBlock(Posotita.oligon_ypsili_aristera, Chronos.klasma, Alloiosi.yfesi_apli, Isokratima.pa, Character.omalon_mono, 'Πα'), // TODO yfesi and isokratima to the right
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'α'),
// 	new PosotitaBlock(Posotita.ison, Character.psifiston, 'α'),
// 	new PosotitaBlock(Posotita.apostrofos, 'α'),
// 	new PosotitaBlock(Posotita.apostrofos_kentimata, 'α'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.apostrofos, 'σα'),
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.apli, Gorgon.gorgon, 'α'),
// 	new PosotitaBlock(Posotita.oligon, 'πνο'),
// 	new PosotitaBlock(Posotita.kentimata, 'ο'),
// 	new PosotitaBlock(Posotita.oligon, Chronos.klasma, Character.psifiston, 'η'),
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'αι'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.ison, 'νε'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ε'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, Gorgon.gorgon_meta, 'σα'), // TODO gorgon position
// 	new PosotitaBlock(Posotita.ison, 'α'),
// 	new PosotitaBlock(Posotita.petasti_elafron, Chronos.klasma, 'τω'),
// 	new PosotitaBlock(Posotita.yporroi, Gorgon.gorgon, 'ω'),
// 	new PosotitaBlock(Posotita.oligon, 'τον'),
// 	new PosotitaBlock(Posotita.oligon, 'Κυ'),
// 	new PosotitaBlock(Posotita.oligon, 'υ'),
// 	new PosotitaBlock(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'υ'),
// 	new PosotitaBlock(Posotita.apostrofos, 'υ'),
// 	new PosotitaBlock(Posotita.apostrofos_kentimata, Gorgon.gorgon, 'υ'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'ρι'),
// 	new PosotitaBlock(Posotita.yporroi, Gorgon.gorgon), // NOTE apostrofos yporroi
// 	new PosotitaBlock(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ι'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ι'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, Character.rythmos_trisimos, 'ον'),
// 	new MartyriaBlock(Fthongos.pa, MartyrikoSimadi.alfa),
// 	new PosotitaBlock(Posotita.ison, 'αι'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.petasti_oligon, Character.rythmos_trisimos, 'νει'),
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'τε'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon, 'το'),
// 	new PosotitaBlock(Posotita.kentimata, 'ον'),
// 	new PosotitaBlock(Posotita.oligon, Chronos.klasma, 'Κυ'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.apostrofos, 'ρι'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ι'),
// 	new PosotitaBlock(Posotita.oligon, 'ι'),
// 	new PosotitaBlock(Posotita.oligon, Chronos.klasma, Isokratima.ke, 'ον'),
// 	new MartyriaBlock(Fthongos.ke, MartyrikoSimadi.alfa_teleies),
// 	new PosotitaBlock(Posotita.ison, Gorgon.gorgon, Fthora.chromatiki_skliri_pa, 'εκ'), // TODO fthora kato
// 	new PosotitaBlock(Posotita.oligon, 'τω'),
// 	new PosotitaBlock(Posotita.kentimata_oligon, Chronos.apli, Character.antikenoma, 'ω'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ων'),
// 	new PosotitaBlock(Posotita.ison_kentimata, Gorgon.gorgon, 'ου'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ου'),
// 	new PosotitaBlock(Posotita.syneches_elafron, 'ρα'),
// 	new PosotitaBlock(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'α'),
// 	new PosotitaBlock(Posotita.apostrofos, 'α'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, Character.rythmos_trisimos, 'νων'),
// 	new MartyriaBlock(Fthongos.ke, MartyrikoSimadi.defteros, Fthora.diatoniki_pa),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon_kentima_dipla, 'αι'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.petasti, Character.rythmos_trisimos, 'νει'),
// 	new PosotitaBlock(Posotita.petasti_apostrofos, Chronos.klasma, 'τε'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.apostrofos, 'α'),
// 	new PosotitaBlock(Posotita.apostrofos, 'αυ'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.apostrofos, Isokratima.melos, 'το'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ο'),
// 	new PosotitaBlock(Posotita.oligon, 'ον'),
// 	new PosotitaBlock(Posotita.oligon, Chronos.klasma, Isokratima.ke, 'εν'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, Gorgon.gorgon, 'τοι'),
// 	new PosotitaBlock(Posotita.apostrofos, 'οις'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, 'υ'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'ψι'),
// 	new PosotitaBlock(Posotita.yporroi, Gorgon.gorgon), // NOTE apostrofos yporroi
// 	new PosotitaBlock(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ι'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ι'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'στοις'),
// 	new MartyriaBlock(Fthongos.ke, MartyrikoSimadi.alfa_teleies, Fthora.diatoniki_ke), // TODO fthora position
// 	new PosotitaBlock(Posotita.oligon_kentima_kato, Character.antikenoma, 'σοι'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, Alloiosi.yfesi_apli, 'πρε'), // NOTE my yfesi
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'πει'),
// 	new PosotitaBlock(Posotita.ison, 'υ'),
// 	new PosotitaBlock(Posotita.kentimata_oligon, Gorgon.gorgon, 'υ'),
// 	new PosotitaBlock(Posotita.elafron, Chronos.klasma, 'μνος'),
// 	new PosotitaBlock(Posotita.oligon, Chronos.klasma, Alloiosi.yfesi_apli, Isokratima.di, Character.psifiston, 'τω'), // TODO yfesi position
// 	new PosotitaBlock(Posotita.yporroi, Gorgon.gorgon, 'ω'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.apostrofos, 'Θε'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ε'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon_kentima_dipla, Chronos.dipli, Isokratima.pa, Character.rythmos_tetrasimos, 'ω'),
// 	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.delta_teleies),
// 	AbstractBlock.newline,
// );

// block_list.push(
// 	new IchosBlock(Ichos.tetartos, Vathmida.pa, Fthora.diatoniki_pa),
// 	AbstractBlock.newline,
// 	new PosotitaBlock(Posotita.petasti_ison, Chronos.klasma, Isokratima.melos, 'Ορ'),
// 	new PosotitaBlock(Posotita.apostrofos, 'θρος'),
// 	new PosotitaBlock(Posotita.yporroi, Gorgon.gorgon), // NOTE apostrofos yporroi
// 	new PosotitaBlock(Posotita.oligon, Isokratima.di_kato, 'η'),
// 	new PosotitaBlock(Posotita.kentimata, 'η'),
// 	new PosotitaBlock(Posotita.petasti, 'η'),
// 	new PosotitaBlock(Posotita.apostrofos, 'η'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ην'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, 'βα'),
// 	new PosotitaBlock(Posotita.yporroi, Gorgon.gorgon, 'α'),
// 	new PosotitaBlock(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'α'),
// 	new PosotitaBlock(Posotita.apostrofos, 'α'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'θυς'),
// 	new MartyriaBlock(Fthongos.di_kato, MartyrikoSimadi.delta),
// 	new PosotitaBlock(Posotita.oligon_ypsili_aristera, Isokratima.vou, 'και'), // TODO isokratima position
// 	SimpleBlock.stavros,
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.ison, 'αι'),
// 	new PosotitaBlock(Posotita.oligon, 'Γυ'),
// 	new PosotitaBlock(Posotita.petasti, Chronos.klasma, 'ναι'),
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.apli, Character.antikenoma, 'κε'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ες'),
// 	new PosotitaBlock(Posotita.petasti_oligon, 'η'),
// 	new PosotitaBlock(Posotita.apostrofos, 'η'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ηλ'),
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, 'θον'),
// 	new MartyriaBlock(Fthongos.vou, MartyrikoSimadi.lambda),
// 	new PosotitaBlock(Posotita.oligon_kentima_dipla, Gorgon.gorgon_kato, Isokratima.pa, 'ε'),
// 	new PosotitaBlock(Posotita.ison, 'πι'),
// 	new PosotitaBlock(Posotita.ison, 'το'),
// 	new PosotitaBlock(Posotita.petasti, 'μνη'),
// 	new PosotitaBlock(Posotita.apostrofos, 'η'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'η'),
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.ison, 'μα'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.digorgon, 'α'),
// 	new PosotitaBlock(Posotita.kentimata, 'α'),
// 	new PosotitaBlock(Posotita.oligon, 'α'),
// 	new PosotitaBlock(Posotita.ison, Gorgon.gorgon, Character.omalon_diplo, 'α'),
// 	new PosotitaBlock(Posotita.apostrofos_kentimata, Gorgon.gorgon, 'σου'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ου'),
// 	new PosotitaBlock(Posotita.syneches_elafron, 'Χρι'),
// 	new PosotitaBlock(Posotita.oligon, Gorgon.gorgon, Character.antikenoma, 'ι'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ι'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, Character.rythmos_trisimos, 'στε'),
// 	new MartyriaBlock(Fthongos.pa, MartyrikoSimadi.alfa),
// 	AbstractBlock.newline,
// );

// block_list.push(
// 	new IchosBlock(Ichos.plagios_tetartos, Vathmida.ni, Fthora.diatoniki_ni),
// 	AbstractBlock.newline,
// 	new PosotitaBlock(Posotita.oligon_kentima_dipla, Isokratima.ni, 'Κυ'),
// 	new PosotitaBlock(Posotita.kentimata_oligon, Gorgon.gorgon, 'υ'),
// 	new PosotitaBlock(Posotita.ison, 'ρι'),
// 	new PosotitaBlock(Posotita.ison, 'ε'),
// 	new PosotitaBlock(Posotita.ison, 'ο'),
// 	new PosotitaBlock(Posotita.kentimata_oligon, Gorgon.gorgon, Alloiosi.yfesi_apli, 'ο'), // TODO yfesi position
// 	new PosotitaBlock(Posotita.elafron, 'πλον'),
// 	new PosotitaBlock(Posotita.ison, 'κα'),
// 	new PosotitaBlock(Posotita.petasti_ison, Fthora.chromatiki_malaki_di, Isokratima.di, 'τα'), // TODO fthora position
// 	new PosotitaBlock(Posotita.apostrofos, Alloiosi.diesi_apli, 'του'),
// 	new PosotitaBlock(Posotita.oligon, 'δι'),
// 	new PosotitaBlock(Posotita.oligon, 'α'),
// 	new PosotitaBlock(Posotita.petasti, 'βο'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ο'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ο'),
// 	new PosotitaBlock(Posotita.ison, Chronos.klasma, 'λου'),
// 	new MartyriaBlock(Fthongos.di, MartyrikoSimadi.defteros_teleies),
// 	new PosotitaBlock(Posotita.ison, Fthora.diatoniki_di, Isokratima.ni, 'τον'),
// 	new PosotitaBlock(Posotita.ison, 'Σταυ'),
// 	new PosotitaBlock(Posotita.petasti_ison, 'ρον'),
// 	new PosotitaBlock(Posotita.apostrofos, 'σου'),
// 	new PosotitaBlock(Posotita.syneches_elafron, 'η'),
// 	new PosotitaBlock(Posotita.kentimata, Gorgon.gorgon_kato, 'η'),
// 	new PosotitaBlock(Posotita.oligon, 'μιν'),
// 	new PosotitaBlock(Posotita.oligon_apostrofos, Character.psifiston, 'δε'),
// 	new PosotitaBlock(Posotita.apostrofos, 'δω'),
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'κας'),
// 	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.delta),
// 	new PosotitaBlock(Posotita.petasti_kentima_ypsili_kentro, Chronos.klasma, Isokratima.di, 'φριτ'), // TODO isokratima position
// 	new PosotitaBlock(Posotita.apostrofos, Alloiosi.yfesi_apli, 'τει'), // NOTE my yfesi
// 	new PosotitaBlock(Posotita.apostrofos, 'ει'),
// 	new PosotitaBlock(Posotita.apostrofos, 'γαρ'),
// 	new PosotitaBlock(Posotita.oligon, 'και'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, Character.psifiston, 'τρε'),
// 	new PosotitaBlock(Posotita.apostrofos, Alloiosi.yfesi_apli, 'ε'), // NOTE my yfesi
// 	new PosotitaBlock(Posotita.apostrofos, 'ε'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, Character.rythmos_trisimos, 'μει'),
// 	new PosotitaBlock(Posotita.oligon, Isokratima.ni, 'μη'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon_apostrofos, Character.psifiston, 'φε'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ρων'),
// 	new PosotitaBlock(Posotita.apostrofos, 'κα'),
// 	new PosotitaBlock(Posotita.oligon, 'θο'),
// 	new PosotitaBlock(Posotita.petasti, 'ραν'),
// 	new PosotitaBlock(Posotita.apostrofos, 'αυ'),
// 	new PosotitaBlock(Posotita.syneches_elafron, 'του'),
// 	new PosotitaBlock(Posotita.kentimata, Gorgon.gorgon_kato, 'ου'),
// 	new PosotitaBlock(Posotita.oligon, 'την'),
// 	new PosotitaBlock(Posotita.oligon_apostrofos, Character.psifiston, 'δυ'),
// 	new PosotitaBlock(Posotita.apostrofos, 'να'),
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'μιν'),
// 	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.delta),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.petasti, Character.rythmos_trisimos, 'ο'),
// 	new PosotitaBlock(Posotita.apostrofos, 'τι'),
// 	new PosotitaBlock(Posotita.ison, 'νε'),
// 	SimpleBlock.diastoli,
// 	SimpleBlock.vareia,
// 	new PosotitaBlock(Posotita.ison, 'κρου'),
// 	new PosotitaBlock(Posotita.apostrofos, Alloiosi.diesi_apli, 'ους'),
// 	new PosotitaBlock(Posotita.oligon, 'α'),
// 	new PosotitaBlock(Posotita.oligon, 'νι'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon, Chronos.klasma, Character.rythmos_trisimos, 'στα'),
// 	new PosotitaBlock(Posotita.ison, 'και'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.oligon_kentima_kato, Character.psifiston, Chroa.zygos, 'θα'),
// 	new PosotitaBlock(Posotita.apostrofos, 'να'),
// 	new PosotitaBlock(Posotita.apostrofos, 'τον'),
// 	new PosotitaBlock(Posotita.apostrofos, 'κα'),
// 	new PosotitaBlock(Posotita.oligon, Character.psifiston, 'τη'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ργη'),
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'σε'),
// 	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.zygos),
// 	new PosotitaBlock(Posotita.oligon_kentima_dipla, Fthora.diatoniki_vou, 'δι'),
// 	new PosotitaBlock(Posotita.oligon, 'α'),
// 	new PosotitaBlock(Posotita.petasti, 'του'),
// 	new PosotitaBlock(Posotita.elafron, 'το'),
// 	new PosotitaBlock(Posotita.oligon, 'προ'),
// 	new PosotitaBlock(Posotita.oligon, 'σκυ'),
// 	new PosotitaBlock(Posotita.oligon_kentimata, Gorgon.gorgon, Alloiosi.yfesi_apli, 'νου'), // NOTE my yfesi
// 	new PosotitaBlock(Posotita.apostrofos, 'ου'),
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.klasma, 'μεν'),
// 	new PosotitaBlock(Posotita.ison, 'την'),
// 	new PosotitaBlock(Posotita.ison, 'τα'),
// 	new PosotitaBlock(Posotita.ison, Character.psifiston, Isokratima.pa, 'φην'),
// 	new PosotitaBlock(Posotita.apostrofos, 'σου'),
// 	new PosotitaBlock(Posotita.apostrofos, 'και'),
// 	new PosotitaBlock(Posotita.apostrofos, 'την'),
// 	new PosotitaBlock(Posotita.oligon_kentima_kato, Character.psifiston, Isokratima.ni, 'ε'),
// 	new PosotitaBlock(Posotita.apostrofos, 'ε'),
// 	new PosotitaBlock(Posotita.apostrofos, Chronos.apli, Character.antikenoma, 'γε'),
// 	new PosotitaBlock(Posotita.apostrofos, Gorgon.gorgon, 'ερ'),
// 	SimpleBlock.diastoli,
// 	new PosotitaBlock(Posotita.ison, Chronos.dipli, Character.rythmos_tetrasimos, 'σιν'),
// 	new MartyriaBlock(Fthongos.ni, MartyrikoSimadi.delta),
// );
